const UPDATED="2026-06-25 12:04";
const CASES=[
 {
  "title": "AI didn't turn me into a 10x dev. It just let me run a whole company by myself",
  "summary": "this meme is basically my life now lol I'm pretty introverted. I hate sales, hate sliding into people's DMs, and I get fried jumping between coding, support, marketing, ops all day. For years that was just a hard cap on what I could do solo. honestly the big thing wasn't AI writing better code. it w",
  "url": "https://www.reddit.com/r/SaaS/comments/1uaf4dw/ai_didnt_turn_me_into_a_10x_dev_it_just_let_me/",
  "source": "r/SaaS",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "AI 沒有讓我變成 10 倍生產力的開發者，它只是讓我一個人就能經營一整間公司",
  "summary_zh": "這個迷因基本上就是我現在的生活寫照 lol。我很內向，討厭業務，討厭私訊別人，而且每天在寫程式、客服、行銷、營運之間切換讓我精疲力盡。多年來，這就是..."
 },
 {
  "title": "Every second post is an ad and I’m sick of pretending it isn’t",
  "summary": "Long gone are the days when using this site used to feel like a community of like-minded people participating in discussion. This subreddit to me seems to be one of the most egregious for it, which is why I’m posting this here. Yes, we are here because we are building SaaS. No, we do not want to buy",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9j28k/every_second_post_is_an_ad_and_im_sick_of/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "每兩篇就有一篇是廣告，我受夠了假裝它不是",
  "summary_zh": "過去那種大家像同好社群一樣討論的日子已經一去不復返了。對我來說，這個 subreddit 是其中最誇張的，這真是..."
 },
 {
  "title": "I got my first paying customer! 🎉",
  "summary": "I only launched a couple of weeks ago, 55 or so free users and now a paid user already 🙌 I wasn't expecting it just yet Edit: it's Cadence if anyone is interested A calm daily planning app built for people with ADHD, autism, or chronic illness who find conventional productivity tools too rigid or ov",
  "url": "https://www.reddit.com/r/SaaS/comments/1uajqa1/i_got_my_first_paying_customer/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-20",
  "title_zh": "我有第一個付費客戶了！🎉",
  "summary_zh": "我才剛上線幾個禮拜，大約 55 個免費使用者，現在就已經有付費使用者了 🙌 我還沒預期到這麼快。補充：如果有人有興趣，這是 Cadence，一款為 p 設計的平靜日常規劃應用程式。"
 },
 {
  "title": "I got my first 4 paying SAAS customers after 3 months of development and organic marketing efforts.",
  "summary": "Just wanted to share with anyone who is on their own SAAS journey, or specifically as a solo founder. It felt like an uphill battle at times trying to get organic traffic and signups to my SAAS but the ball finally feels like it's rolling; without paying anything for paid ads or marketing. For conte",
  "url": "https://www.reddit.com/r/SaaS/comments/1udb7ro/i_got_my_first_4_paying_saas_customers_after_3/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-23",
  "title_zh": "我開發並透過自然行銷推廣三個月後，獲得了首批 4 位付費 SaaS 客戶。",
  "summary_zh": "想跟所有正在踏上 SaaS 之旅，特別是獨立創辦人分享。有時候，要為我的 SaaS 帶來自然流量和註冊，感覺就像一場硬仗，但..."
 },
 {
  "title": "First revenue!!!",
  "summary": "yay",
  "url": "https://www.reddit.com/r/SaaS/comments/1udkhq5/first_revenue/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-23",
  "title_zh": "首次營收！！！",
  "summary_zh": "耶！"
 },
 {
  "title": "Cursor was launched 8 time before $60 billion ACQ",
  "summary": "Never Give up on your Journey",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9ergx/cursor_was_launched_8_time_before_60_billion_acq/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "Cursor 在被 $60 億美元收購前，曾推出 8 次",
  "summary_zh": "永不放棄你的旅程"
 },
 {
  "title": "i lost my stripe virginity… 🤑",
  "summary": "last week I launched my first ever vibe coded app. a little marketing game where people fight for ad space. and two people have now paid to play. total revenue: $2.62 a little shocked because you can play the game for free… but im feeling very grateful to whoever my first 2 customers were 🫡 this is ",
  "url": "https://www.reddit.com/r/SaaS/comments/1ue0m42/i_lost_my_stripe_virginity/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-24",
  "title_zh": "我第一次用 Stripe 收款了… 🤑",
  "summary_zh": "上週我推出了我的第一個 vibe coded 應用程式。這是一個小型的行銷遊戲，玩家在其中爭奪廣告版位。現在已經有兩個人付費玩了。總收入：$2.62。我有點震驚，因為你可以..."
 },
 {
  "title": "My SaaS just made its first $33. I paid myself $13, and a friend threw in $20 for morale. Honestly? It works.",
  "summary": "Hey everyone, I wanted to share a small but incredibly motivating milestone today. After months of development, I officially processed a $13 payout from my platform into my bank account. To add to the momentum, a close friend bought a $20 tier purely as a motivational gesture to keep me moving forwa",
  "url": "https://www.reddit.com/r/SaaS/comments/1ua0cnq/my_saas_just_made_its_first_33_i_paid_myself_13/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "我的 SaaS 剛賺到第一筆 $33。我付給自己 $13，一個朋友為了鼓勵我給了 $20。老實說？它奏效了。",
  "summary_zh": "大家好，今天我想分享一個雖小但極具激勵意義的里程碑。經過數月的開發，我正式從我的平台提領了 $13 到我的銀行帳戶。除此之外..."
 },
 {
  "title": "every b2b founder on reddit",
  "summary": "genuine question because i feel like i'm losing my mind a little how are you actually supposed to market a b2b saas and get sales coming in directly, not in six months, now every place i go to find customers is full of other founders trying to do the exact same thing to me everywhere i show up to ta",
  "url": "https://www.reddit.com/r/SaaS/comments/1ucv7zx/every_b2b_founder_on_reddit/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-22",
  "title_zh": "Reddit 上每個 B2B 創辦人",
  "summary_zh": "這是個真誠的問題，因為我感覺自己快要瘋了，到底該如何行銷 B2B SaaS 並立即獲得銷售，而不是等六個月後？我尋找客戶的每個地方..."
 },
 {
  "title": "Do you have a backup plan if you SaaS fails (if you're in your ~40s)?",
  "summary": "I'll be honest, I'm losing sleep over this for the past few weeks. The uncertainty is at its peak and I can't pretend it isn't affecting me. I'm someone who's got ~20 years of professional experience across domains. I've worked for corporates and also built a lifestyle startup that made money for go",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9se41/do_you_have_a_backup_plan_if_you_saas_fails_if/",
  "source": "r/SaaS",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "如果你的 SaaS 失敗了，你有備用計畫嗎（如果你 40 歲左右）？",
  "summary_zh": "老實說，過去幾週我為此失眠。不確定性達到頂峰，我無法假裝它沒有影響我。我是一個擁有大約 20 年專業經驗的人..."
 },
 {
  "title": "Got my solo translation app to $10k MRR. Some random notes after 8 months",
  "summary": "Solo dev from Japan here. Not Tokyo, not really in any startup scene, just building from a more rural area. I launched a translation app in Oct 2025 and it recently passed $10k MRR. took around 8 months. proof: https://profile.stripe.com/nani/Ae1hNCkN No ads, no paid referral thing, no big launch. m",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9o3gv/got_my_solo_translation_app_to_10k_mrr_some/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": "$10k MRR",
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "我的個人翻譯 App 達到 $10k MRR。8 個月後的一些隨筆",
  "summary_zh": "我是來自日本的個人開發者。不是東京，也不是什麼新創圈，只是在比較鄉下的地方開發。我在 2025 年 10 月推出了一個翻譯 App，最近它達到了 $10k MRR，花了大概 8 個月..."
 },
 {
  "title": "They launched cursor 8 times and nobody cared. True definition of never give up",
  "summary": "https://preview.redd.it/iqhvtbmrf18h1.png?width=680&format=png&auto=webp&s=ff08a195fd636e0597808c21fff36bac9d3b05d3",
  "url": "https://www.reddit.com/r/SaaS/comments/1u95fde/they_launched_cursor_8_times_and_nobody_cared/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "他們推出了 Cursor 8 次，卻沒人在乎。這才是永不放棄的真正定義",
  "summary_zh": "https://preview.redd.it/iqhvtbmrf18h1.png?width=680&format=png&auto=webp&s=ff08a195fd636e0597808c21fff36bac9d3b05d3"
 },
 {
  "title": "Our SEO peaked at 20K clicks/month in 2024. Now it barely reaches 7K. Here's what I think happened.",
  "summary": "A while back, I posted in another sub about my brother fixing a content plateau on my SaaS by deleting 40% of our SEO content. And because of that, our clicks had gone from 4,000 to 12,000 within 90 days. But what I never shared is what happened after. Late 2023, I’d hired a new marketing team and g",
  "url": "https://www.reddit.com/r/SaaS/comments/1udm86e/our_seo_peaked_at_20k_clicksmonth_in_2024_now_it/",
  "source": "r/SaaS",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-23",
  "title_zh": "我們的 SEO 在 2024 年曾達到每月 2 萬次點擊的高峰，現在卻勉強只有 7 千次。我認為原因如下。",
  "summary_zh": "不久前，我在另一個社群發文提到我弟弟透過刪除 40% 的 SEO 內容，解決了我的 SaaS 內容停滯問題。因此，我們的點擊量在 90 天內從 4,000 增加到 12,000..."
 },
 {
  "title": "Strangers are paying for something I built and it feels weird",
  "summary": "This is probably not a huge milestone for most people here, but it feels pretty surreal to me: a few people I don’t know are now paying for something I built. Not friends, not people I convinced in DMs, not someone I had a call with. Actual strangers. They landed on the product, created an account, ",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9cbht/strangers_are_paying_for_something_i_built_and_it/",
  "source": "r/SaaS",
  "category": "工作流自動化",
  "mrr": "$50k MRR",
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "陌生人為我打造的東西付錢，感覺很奇怪",
  "summary_zh": "這對這裡大多數人來說可能不是什麼大里程碑，但對我來說感覺非常不真實：一些我不認識的人現在正在為我打造的東西付費。不是朋友，也不是我私訊說服的人..."
 },
 {
  "title": "Let's gooo over 100 users in 30min",
  "summary": "Hey guys, next milestone is achieved! Over 100 customer in 30 minutes online. Feels great, but still alot to do! This journey never ends. When i started, I had this wrong thesis that you finish your app and its done, no work more to do. But is there a point when you really \"finish\" your saas? Becaus",
  "url": "https://www.reddit.com/r/SaaS/comments/1u92p6h/lets_gooo_over_100_users_in_30min/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "太棒了！30 分鐘內就超過 100 個使用者",
  "summary_zh": "各位，下一個里程碑達成了！30 分鐘內線上客戶超過 100 位。感覺很棒，但還有很多事要做！這趟旅程永無止境。我剛開始時，有個錯誤的假設，以為你完成你的..."
 },
 {
  "title": "The way I got my first paying user on my SaaS",
  "summary": "I searched on X and Reddit about who is facing the problem that my product solves, and DMed 50+ people and got one conversion out of it.",
  "url": "https://www.reddit.com/r/SaaS/comments/1ucg8ks/the_way_i_got_my_first_paying_user_on_my_saas/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-22",
  "title_zh": "我如何在我的 SaaS 上獲得第一個付費使用者",
  "summary_zh": "我在 X 和 Reddit 上搜尋誰正遇到我的產品能解決的問題，並私訊了 50 多人，其中一人成功轉換。"
 },
 {
  "title": "After months of building my first SaaS, I finally understood that building is the easy part",
  "summary": "I spent the last few months building my first SaaS as a solo founder. When I started, I thought the hardest part would be the coding. I was wrong. The product side was challenging, but there were clear problems and clear solutions. You fix a bug, improve the UX, optimize performance and move forward",
  "url": "https://www.reddit.com/r/SaaS/comments/1uc018i/after_months_of_building_my_first_saas_i_finally/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-21",
  "title_zh": "打造我的第一個 SaaS 數個月後，我終於明白打造產品是比較簡單的部分",
  "summary_zh": "在過去幾個月裡，我以獨立創辦人的身份打造我的第一個 SaaS。一開始，我以為最困難的部分會是寫程式。我錯了。產品面雖然充滿挑戰，但有明確的..."
 },
 {
  "title": "Made my first Sale on my new SaaS",
  "summary": "I built this SaaS in less than 12 hours and got my first Sale on it! I am just so happy!!",
  "url": "https://www.reddit.com/r/SaaS/comments/1ubsm0r/made_my_first_sale_on_my_new_saas/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-21",
  "title_zh": "我的新 SaaS 產品達成了第一筆銷售。",
  "summary_zh": "我在不到 12 小時內開發了這個 SaaS 產品，並達成了第一筆銷售！我真是太開心了！！"
 },
 {
  "title": "Sent 50 cold emails. Got 0 replies. How did you get your first users?",
  "summary": "Over the last week I've been building a SaaS product and recently launched the first working version. After launching, I started reaching out to potential users for feedback. So far I've sent around 50 emails and got almost no responses. One person tested the product and said it was useful, but that",
  "url": "https://www.reddit.com/r/SaaS/comments/1udcywf/sent_50_cold_emails_got_0_replies_how_did_you_get/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-23",
  "title_zh": "寄了 50 封陌生開發信，0 回覆。你們是怎麼找到第一批使用者的？",
  "summary_zh": "過去一週我一直在開發一個 SaaS 產品，最近推出了第一個可運作的版本。上線後，我開始聯繫潛在使用者以獲取回饋。到目前為止，我已經寄了大概 5..."
 },
 {
  "title": "I launched my first SaaS 7 days ago - 77 visitors, 13 signups, and a big lesson about distribution",
  "summary": "After launching my first SaaS (LangSpeak) and sharing it on founder communities, here are the results from the first 7 days: • 77 visitors • 71 first-time visitors • 13 signups • Users from multiple countries • Several bug reports and feature suggestions The most interesting part: Getting people to ",
  "url": "https://www.reddit.com/r/SaaS/comments/1ubkt27/i_launched_my_first_saas_7_days_ago_77_visitors/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-21",
  "title_zh": "我在七天前推出了我的第一個 SaaS 產品——77 位訪客、13 次註冊，以及關於通路的一大教訓。",
  "summary_zh": "在推出我的第一個 SaaS 產品 (LangSpeak) 並在創業者社群分享後，這是前七天的成果：• 77 位訪客 • 71 位首次訪客 • 13 次註冊 • 來自多個國家/地區的使用者..."
 },
 {
  "title": "How do you market or promote your SaaS product?",
  "summary": "I'm curious how other bootstrapped SaaS founders are getting their first 10-100 paying customers. There seems to be a huge gap between \"build the product\" and \"people actually find it.\" For those of you running a SaaS: What marketing channels are working best for you right now? How much traffic/cust",
  "url": "https://www.reddit.com/r/SaaS/comments/1ubrgw4/how_do_you_market_or_promote_your_saas_product/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-21",
  "title_zh": "你的 SaaS 產品是如何行銷或推廣的？",
  "summary_zh": "我很好奇其他白手起家的 SaaS 創辦人是如何獲得他們最初的 10-100 位付費客戶。在「開發產品」和「讓大家真正找到產品」之間似乎存在著巨大的鴻溝。對於那些..."
 },
 {
  "title": "How do you actually find real problems worth solving?",
  "summary": "I've been trying to build a SaaS, but I'm stuck on one thing: I just can't seem to find real problems that people have. Everyone says things like: \"Talk to users.\" \"Find pain points.\" \"Solve your own problem.\" But when I talk to people, they usually say everything is fine or they don't have anything",
  "url": "https://www.reddit.com/r/SaaS/comments/1ucps42/how_do_you_actually_find_real_problems_worth/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-22",
  "title_zh": "你究竟如何找到真正值得解決的問題？",
  "summary_zh": "我一直想開發一個 SaaS，但卡在一個問題上：我似乎找不到人們遇到的真正問題。每個人都說：「跟使用者聊聊。」「找出痛點。」「解決你自己的問題。」"
 },
 {
  "title": "It took 25 days to make my first €16. Here's everything I did.",
  "summary": "25 days ago I pushed my first commit to GitHub for my new SaaS app. Today I made my first sale of €16. I know it’s not much but after grinding away for almost a month its feels amazing that someone has actually decided to pay for what I built. Here’s how I got here: - The Idea With a high rise of pe",
  "url": "https://www.reddit.com/r/SaaS/comments/1uc0fmy/it_took_25_days_to_make_my_first_16_heres/",
  "source": "r/SaaS",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-21",
  "title_zh": "我花了 25 天賺到我的第一筆 €16。這是我所做的一切。",
  "summary_zh": "25 天前，我將我的第一個 commit 推送到 GitHub，用於我的新 SaaS 應用程式。今天我完成了第一筆 €16 的銷售。我知道這不算多，但在努力了將近一個月後，有人... 這種感覺真是太棒了。"
 },
 {
  "title": "I'm about to quit the whole SaaS thing, and I don't want to",
  "summary": "I've been pretty demotivated with the whole SaaS thing for a while now. I've spent months reading up, watching videos, and trying to build some kind of tool. The thing is, I never manage to finish any project I lose motivation, or I find a thousand problems that make me think it won't be worth it. A",
  "url": "https://www.reddit.com/r/SaaS/comments/1ucgrgk/im_about_to_quit_the_whole_saas_thing_and_i_dont/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-22",
  "title_zh": "我快要放棄整個 SaaS 事業了，但我不想這樣",
  "summary_zh": "一段時間以來，我對整個 SaaS 事業感到非常沮喪。我花了數個月閱讀、觀看影片，並嘗試打造某種工具。問題是，我從來沒有完成任何..."
 },
 {
  "title": "What was your life like after reaching $10K MRR in your SaaS business?",
  "summary": "I'm currently building a B2B SaaS and working toward my first $10K MRR milestone. As someone based in India, that level of recurring revenue with healthy SaaS margins would be quite meaningful financially. I'd love to hear from founders (especially solo founders or small teams) who have already cros",
  "url": "https://www.reddit.com/r/SaaS/comments/1ubr57w/what_was_your_life_like_after_reaching_10k_mrr_in/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": "$10K MRR",
  "points": 0,
  "comments": 0,
  "date": "2026-06-21",
  "title_zh": "你的 SaaS 事業達到每月經常性收入 (MRR) $10K 後，生活是怎麼樣的？",
  "summary_zh": "我目前正在開發一個 B2B SaaS 產品，並努力達成我的第一個 $10K MRR 里程碑。作為一個在印度的人，這種健康的 SaaS 利潤率所帶來的經常性收入水平，在財務上將會非常有意義。"
 },
 {
  "title": "How do you reach potential customers when you have no social media following?",
  "summary": "Hi everyone, I'm in the early stages of starting a business and I'm struggling with customer acquisition. I don't have an existing audience, no large social media following, and no email list. It feels like every marketing advice starts with \"post consistently on social media,\" but starting from zer",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9h21f/how_do_you_reach_potential_customers_when_you/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "當你沒有社群媒體追蹤者時，如何觸及潛在客戶？",
  "summary_zh": "大家好，我正處於創業初期，在客戶獲取方面遇到困難。我沒有現有的受眾，沒有大量的社群媒體追蹤者，也沒有電子郵件列表。感覺..."
 },
 {
  "title": "I built a job search tool during my layoff and it just crossed $10k",
  "summary": "During my layoff in Feb 2023, I had a hard time finding jobs through LinkedIn, indeed, and other services. The listings were old and usually had hundreds of applicants. After a few months, I landed on a super simple process that I created in Notion that got me more interviews. Over one weekend, I co",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9ch2z/i_built_a_job_search_tool_during_my_layoff_and_it/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "我被裁員期間開發的求職工具，營收已突破 $10k",
  "summary_zh": "2023 年 2 月我被裁員時，透過 LinkedIn、indeed 等服務找工作很不順利。職缺資訊很舊，通常都有數百人應徵。幾個月後，我發現了"
 },
 {
  "title": "I’ve sent 200 cold emails and got 0 real leads, now what?",
  "summary": "Long story short: I built a way for small businesses to see where their money's going, track unnecessary spending, and find out what to actually do about it. You drop in a bank or card statement (CSV, Excel, or a PDF), and it gives you a plain-English rundown of where money's quietly leaking, and wh",
  "url": "https://www.reddit.com/r/SaaS/comments/1ue2i6f/ive_sent_200_cold_emails_and_got_0_real_leads_now/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-24",
  "title_zh": "我寄了 200 封陌生開發信，卻沒有任何實際的潛在客戶，現在該怎麼辦？",
  "summary_zh": "長話短說：我開發了一個工具，讓小型企業能清楚掌握資金流向、追蹤不必要的開支，並找出實際的解決方案。你只要匯入銀行或信用卡對帳單 (CSV 格式，..."
 },
 {
  "title": "How I scaled a free utility platform to 425K active users (and 6,200+ concurrent) with practically zero server bills. Here’s the architecture.",
  "summary": "Hey r/SaaS , I wanted to share a quick breakdown of how I’ve been scaling my web utility platform over the last few months. As you can see from my GA4 dashboard screenshot attached, we just hit 425K active users over the past 30 days, processing 12.7M events , with real-time concurrency consistently",
  "url": "https://www.reddit.com/r/SaaS/comments/1uarzd8/how_i_scaled_a_free_utility_platform_to_425k/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-20",
  "title_zh": "我如何將一個免費工具平台擴展到 425K 活躍使用者 (以及超過 6,200 個同時在線使用者)，且幾乎零伺服器費用。這是它的架構。",
  "summary_zh": "嗨，r/SaaS，我想快速分享一下我這幾個月來是如何擴展我的網路工具平台的。如同我附上的 GA4 儀表板截圖所示，我們剛達到 425K 的..."
 },
 {
  "title": "Google Ads are a con. Prove me wrong.",
  "summary": "Every year or so, I come back to paid ads.... I get sucked into the BS that Google sells and think, \"I'll give it one more go\", and every F**KING time Google wastes my money on BS traffic. In any other industry, what they do would be illegal. You can't walk into a restaurant and say \" I want the ste",
  "url": "https://www.reddit.com/r/SaaS/comments/1udaa8t/google_ads_are_a_con_prove_me_wrong/",
  "source": "r/SaaS",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-23",
  "title_zh": "Google 廣告是個騙局。證明我錯了。",
  "summary_zh": "每年左右，我都會回頭嘗試付費廣告... 我被 Google 推銷的鬼話吸引，心想「我再試一次」，結果每次 Google 都把我的錢浪費在垃圾流量上。在任何其他..."
 },
 {
  "title": "Successful SaaS founders: Did you know the industry beforehand or was it just a random niche?",
  "summary": "I’ve been completely stuck for a few months now and I can't seem to finish anything. I start projects, but I always end up dropping them because I don't see the potential or the idea just stops making sense. I see that the standard advice for building a SaaS is to look into your own problems, but th",
  "url": "https://www.reddit.com/r/SaaS/comments/1ud9sv2/successful_saas_founders_did_you_know_the/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-23",
  "title_zh": "成功的 SaaS 創辦人：你們是事先了解該產業，還是只是隨機選擇了一個利基市場？",
  "summary_zh": "我已經完全卡住好幾個月了，似乎無法完成任何事情。我會開始專案，但總是半途而廢，因為我看不到潛力，或者這個想法就失去意義了..."
 },
 {
  "title": "Built the product, now staring at an empty stripe dashboard. How did you actually figure out distribution?",
  "summary": "Hey guys, Standard dev story here. Spent the last few months head-down building out a web app. The tech stack is solid, everything works perfectly in production, and it's officially live. But now that the building part is over, I’m hitting a massive wall. I have absolutely zero experience with marke",
  "url": "https://www.reddit.com/r/SaaS/comments/1ua0qmt/built_the_product_now_staring_at_an_empty_stripe/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "產品開發完成了，卻看著空蕩蕩的 Stripe 後台。你們是怎麼找到推廣管道的？",
  "summary_zh": "大家好，這是一個很典型的開發者故事。過去幾個月我埋頭開發一個網路應用程式，技術堆疊很穩固，在正式環境中一切運作完美，也正式上線了。但現在"
 },
 {
  "title": "Need brutal customer reviews for my first Saas",
  "summary": "I was also a typical SWE 9-5, used to rant with coworkers about \"one day I'll start my own thing,\" go home, doomscroll, sleep, repeat. Classic. Then one night I had the thought every founder apparently has at 2am: founders run 3-4 companies simultaneously and somehow survive, why am I acting like I ",
  "url": "https://www.reddit.com/r/SaaS/comments/1ubzif8/need_brutal_customer_reviews_for_my_first_saas/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-21",
  "title_zh": "我的第一個 SaaS 產品需要嚴苛的客戶評論",
  "summary_zh": "我也曾是個朝九晚五的典型軟體工程師 (SWE)，以前常跟同事抱怨說「總有一天我要自己創業」，然後回家，滑手機看負面新聞，睡覺，日復一日。很經典的模式。然後有一天晚上，我突然有了每個創辦人似乎都會有的想法..."
 },
 {
  "title": "Got my first dollar",
  "summary": "I don’t have any premium or subscription model on my iOS app, pretty much just put a donation jar. Which I suppose makes it even sweeter that someone wanted to give me a buck just to say thanks! project: geospoof.com",
  "url": "https://www.reddit.com/r/SaaS/comments/1ub5ml4/got_my_first_dollar/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-20",
  "title_zh": "我賺到我的第一塊錢了",
  "summary_zh": "我的 iOS 應用程式沒有任何付費或訂閱模式，基本上就只是放了一個捐款箱。所以有人願意給我一塊錢只為了說聲謝謝，這讓我覺得更開心！proje"
 },
 {
  "title": "I posted on 200 directories and turned it into a living curated list anyone can use",
  "summary": "I believe in submitting to directories, like Producthun Peerlist etc., both for the traffic they deliver and for the SEO and GEO benefits. But it's a grind. There are a lot of directories out there, and many turn out to be pretty useless while others are great. So over time I kept an Excel sheet tra",
  "url": "https://www.reddit.com/r/indiehackers/comments/1u9yr7f/i_posted_on_200_directories_and_turned_it_into_a/",
  "source": "r/indiehackers",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "我在 200 個目錄網站上發布了我的產品，並將其變成一個任何人都可以使用的持續更新精選清單",
  "summary_zh": "我相信提交到 Producthun、Peerlist 等目錄網站，不僅能帶來流量，還有助於 SEO 和 GEO。但這是一項苦差事，外面有很多目錄網站，而"
 },
 {
  "title": "One-time Purchase or Free Game with Ads",
  "summary": "Hello everyone! Recently, I participated in a hackathon and developed a web game to compete in the hackathon. It is a game similar to Block Blast! and Tetris, with some unique twists. I actually sent it to a few of my friends, and many loved it, which is why I am currently thinking of developing it ",
  "url": "https://www.reddit.com/r/indiehackers/comments/1ua42uh/onetime_purchase_or_free_game_with_ads/",
  "source": "r/indiehackers",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "一次性購買，還是內含廣告的免費遊戲？",
  "summary_zh": "大家好！最近我參加了一個黑客松，開發了一款網頁遊戲來參賽。這是一款類似 Block Blast! 和 Tetris 的遊戲，帶有一些獨特的變化。我實際上發送了"
 },
 {
  "title": "Got 272 founders to sign up. The hard part was everything after that",
  "summary": "We launched our fundraising tool for founders around 40 days ago and I thought the hard part would be getting people to sign up. Lol no. We got 272 founders into the product, which felt pretty good for about 5 minutes. Then we looked at the funnel properly: 272 signed up 253 created a company profil",
  "url": "https://www.reddit.com/r/indiehackers/comments/1ue9h6e/got_272_founders_to_sign_up_the_hard_part_was/",
  "source": "r/indiehackers",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-24",
  "title_zh": "成功讓 272 位創辦人註冊。但困難的部分是之後的一切",
  "summary_zh": "大約 40 天前，我們推出了為創辦人設計的募資工具，我原以為最困難的是讓大家註冊。結果不是。我們成功讓 272 位創辦人開始使用產品，感覺還不錯..."
 },
 {
  "title": "Vibe coding a social media SaaS? We built an MCP server that can manage unlimited accounts",
  "summary": "Yooo, The title is a little bit of clickbait because my actual intention was more along the lines of \"vibe coders struggled, so we helped them.\" This is supposed to be a tutorial post. Why? Because a lot of people building things today aren't programmers at heart, and the struggle is real. We get hu",
  "url": "https://www.reddit.com/r/indiehackers/comments/1udibld/vibe_coding_a_social_media_saas_we_built_an_mcp/",
  "source": "r/indiehackers",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-23",
  "title_zh": "隨性寫社群媒體 SaaS？我們建了一個能管理無限帳號的 MCP 伺服器",
  "summary_zh": "嘿，標題有點點擊誘餌的成分，因為我真正的意圖更像是「隨性寫程式的人遇到困難，所以我們幫助他們。」這應該是一篇教學文章。為什麼？因為一個..."
 },
 {
  "title": "Just hit 💲73 in revenue with 40 users!",
  "summary": "Quick stats: $73 total revenue (yes it's not $7.3k) 40 users (6 paying users + 34 free users just trying out) Still working hard to get organic traffic. Fixed four bugs and one minor Quality-of-life feature that paying users requested Not much, but seeing people actually pay for what I built feels a",
  "url": "https://www.reddit.com/r/SideProject/comments/1ucpcct/just_hit_73_in_revenue_with_40_users/",
  "source": "r/SideProject",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-22",
  "title_zh": "剛達到 💲73 的營收，擁有 40 個使用者！",
  "summary_zh": "快速統計：總營收 💲73 (是的，不是 💲7.3k)。40 個使用者 (6 個付費使用者 + 34 個免費試用者)。仍在努力獲取自然流量。修復了四個錯誤和一個小的生活品質..."
 },
 {
  "title": "I spent 6 months building an interactive image map editor with a Figma-like UI",
  "summary": "Hello everyone! While traditional WordPress image map tools like WP Draw Attention, Mapplic, or ImageMap Pro get the job done, their interfaces haven't fully caught up with modern web standards. My goal was to create an alternative that brings a snappy, desktop-class experience right into the browse",
  "url": "https://www.reddit.com/r/SideProject/comments/1uarlyp/i_spent_6_months_building_an_interactive_image/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-20",
  "title_zh": "我花了 6 個月打造一個具有類似 Figma 使用者介面的互動式圖片地圖編輯器",
  "summary_zh": "大家好！雖然傳統的 WordPress 圖片地圖工具，像是 WP Draw Attention、Mapplic 或 ImageMap Pro 都能完成工作，但它們的介面還沒有完全跟上現代網路標準。我的..."
 },
 {
  "title": "drop your project below — I'll genuinely try it and give you real feedback",
  "summary": "been heads-down building solo for months and just got my first app onto testflight, and the thing I've missed most is actually using other people's stuff and talking to the people building it. so let's do that. drop your project below — app, SaaS, tool, game, whatever. I'll go through as many as I c",
  "url": "https://www.reddit.com/r/SideProject/comments/1u9op89/drop_your_project_below_ill_genuinely_try_it_and/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "在下面留下你的專案 — 我會真心試用並給你真實的回饋",
  "summary_zh": "過去幾個月我一直埋頭獨自開發，剛把我的第一個應用程式上架到 TestFlight。我最想念的是實際使用別人的產品並與開發者交流。所以讓"
 },
 {
  "title": "I made my first money from a vibecoded side project, and it made me feel better than closing huge deals for my main business",
  "summary": "Hey everyone! Recently I made a tool that turns agents into playable RPG characters. This project was started when I realized that, as a gamer, the standard setup I had with VS Code and agents built in there was too boring and… kind of missing that “alive” feel? Like, I was using them on a daily bas",
  "url": "https://www.reddit.com/r/SideProject/comments/1ua6t1g/i_made_my_first_money_from_a_vibecoded_side/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "我從一個憑感覺開發的副業專案賺到了第一筆錢，這讓我比主業談成大筆交易還要開心",
  "summary_zh": "大家好！最近我開發了一個工具，能將代理程式變成可玩的 RPG 角色。這個專案的開始，是因為我意識到，作為一個玩家，我使用 VS Code 和內建代理程式的標準設定"
 },
 {
  "title": "I built a Claude Code skill called /brag that turns your side project into a launch video",
  "summary": "People around me keep telling me about cool stuff they built but it often ends at that, so I built /brag, a skill that helps people actually show what they made. /brag lets you brag about what you built by simply telling Claude \"hey, let's /brag about this.\" Under the hood it uses HyperFrames (HeyGe",
  "url": "https://www.reddit.com/r/SideProject/comments/1ubr7ng/i_built_a_claude_code_skill_called_brag_that/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-21",
  "title_zh": "我開發了一個名為 /brag 的 Claude Code 技能，能將你的副業專案變成發布影片。",
  "summary_zh": "我身邊的人不斷告訴我他們開發的酷東西，但通常就到此為止了，所以我開發了 /brag，這是一個能幫助人們實際展示他們所做成果的技能。/brag 讓你能夠炫耀你開發的..."
 },
 {
  "title": "I built an open-source Random Number Generator",
  "summary": "I’m currently a third-year Software Engineering student, and I recently decided to combine my interest in algorithms and chaos theory into a fun experimental side project. I built BSG Random Number Generator , a pseudo-random number generator (PRNG) entirely powered by the chaotic orbits of the famo",
  "url": "https://www.reddit.com/r/SideProject/comments/1uaeg4v/i_built_an_opensource_random_number_generator/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "我打造了一個開源的亂數產生器",
  "summary_zh": "我目前是一名三年級的軟體工程系學生，我最近決定將我對演算法和混沌理論的興趣結合，做成一個有趣的實驗性副專案。我打造了 BSG Random Number Ge..."
 },
 {
  "title": "My latest app made the front page on Hacker News today!",
  "summary": "My puzzle site ( https://PuzzleLair.com ) made the front page on Hacker News today (still there as I type this)! Google Analytics showed up to 500 real time users every half hour for a few hours. I was worried that my little VPS that's running 8 other apps would tank, but it held up. I know it's not",
  "url": "https://www.reddit.com/r/SideProject/comments/1ud13g8/my_latest_app_made_the_front_page_on_hacker_news/",
  "source": "r/SideProject",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-22",
  "title_zh": "我最新的應用程式今天登上了 Hacker News 頭版！",
  "summary_zh": "我的益智網站 ( https://PuzzleLair.com ) 今天登上了 Hacker News 頭版 (我打字時還在上面)！Google Analytics 顯示在幾個小時內，每半小時有高達 500 個即時使用者。我..."
 },
 {
  "title": "Took me 4 years and 3 dead side projects to learn what actually matters",
  "summary": "I built my first side project in 2022. It was a habit tracker with a twist — you'd compete against friends. I spent six months obsessing over the UI, the animations, the perfect onboarding flow. Launched it to crickets. Maybe 12 signups, all friends and family. Dead in a month. Project number two wa",
  "url": "https://www.reddit.com/r/SideProject/comments/1ue2bm5/took_me_4_years_and_3_dead_side_projects_to_learn/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-24",
  "title_zh": "我花了 4 年和 3 個失敗的副業專案，才學到真正重要的事",
  "summary_zh": "我在 2022 年開發了我的第一個副業專案。這是一個帶有特殊玩法的習慣追蹤器——你可以和朋友競爭。我花了六個月的時間，沉迷於使用者介面、動畫和完美的引導流程。Launc"
 },
 {
  "title": "We overestimate what we can accomplish in one day, but drastically underestimate what a full year of daily consistency brings. If you had to commit to ONE daily habit nonstop for an entire year—what would you pick?",
  "summary": "I’ve been stuck in this mindset trap so many times lately. Everyone hypes up grinding hard for a single day, pulling an all-nighter or cramming a huge to-do list, thinking that one burst of effort will change everything. But in reality, that one-day push barely moves the needle at all. Meanwhile, sh",
  "url": "https://www.reddit.com/r/SideProject/comments/1uapu08/we_overestimate_what_we_can_accomplish_in_one_day/",
  "source": "r/SideProject",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-20",
  "title_zh": "我們高估了一天內能完成的事情，但卻嚴重低估了整整一年每天堅持不懈所帶來的成果。如果你必須堅持一個日常習慣一整年不間斷——你會選擇什麼？",
  "summary_zh": "我最近常常陷入這種思維陷阱。大家都喜歡鼓吹一天內努力衝刺、熬夜或塞滿一大堆待辦事項，認為一次爆發性的努力就能..."
 },
 {
  "title": "I'm testing a \"one tiny thing a day\" before building anything",
  "summary": "I'm a builder, 15 years in product + tech. I know what I should do, I just can't start, and the evening disappears into scrolling. The idea: once a day you get one tiny nudge to do a small thing, small enough that starting is basically impossible to fail. Stand outside two minutes. Open the task you",
  "url": "https://www.reddit.com/r/SideProject/comments/1ubmta1/im_testing_a_one_tiny_thing_a_day_before_building/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-21",
  "title_zh": "在開始開發任何東西之前，我正在測試「每天做一件小事」的方法。",
  "summary_zh": "我是一名開發者，在產品和科技領域有 15 年經驗。我知道我該做什麼，但我就是無法開始，晚上時間都浪費在滑手機上了。這個想法是：每天你會收到一個小小的提示，去做一件小事，小到..."
 },
 {
  "title": "Launched LyteNyte, a 40KB data grid with 150+ features capable of rendering millions of rows at 60 FPS",
  "summary": "Hey guys, I wanted to share LyteNyte Grid, a powerful React data grid component library we’ve been developing. We are currently on v.2.1, and v.2.2 will be released at the end of this month. There are other popular React data grid libraries, but LyteNyte Grid is, in our opinion, the best (biased vie",
  "url": "https://www.reddit.com/r/SideProject/comments/1u9u1y8/launched_lytenyte_a_40kb_data_grid_with_150/",
  "source": "r/SideProject",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "推出 LyteNyte：一個 40KB 的資料網格，擁有超過 150 種功能，能以 60 FPS 渲染數百萬行資料",
  "summary_zh": "大家好，我想分享 LyteNyte Grid，這是一個我們一直在開發的強大 React 資料網格元件庫。我們目前是 v.2.1 版本，v.2.2 將於本月底發布。有"
 },
 {
  "title": "I spent two years building a 100% free alternative to Splitwise.",
  "summary": "Hi everyone, I believe a basic utility like splitting expenses with friends and family should be free. When Splitwise paywalled their core features and started adding dark patterns, I looked for alternatives but found nothing with an intuitive UX. So, I built Divy. The thing I'm most proud of, is th",
  "url": "https://www.reddit.com/r/SideProject/comments/1uc8itf/i_spent_two_years_building_a_100_free_alternative/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-22",
  "title_zh": "我花了兩年時間打造一個 100% 免費的 Splitwise 替代方案。",
  "summary_zh": "大家好，我認為像與朋友和家人分攤費用這樣的基本工具應該是免費的。當 Splitwise 將其核心功能設為付費牆並開始增加暗黑模式時，我尋找了替代方案..."
 },
 {
  "title": "I built AuditMetric: A free website auditor with unlimited CVE security checks. No monthly subscription.",
  "summary": "Hey r/SideProject , I got tired of site audit tools putting basic security and health scans behind expensive paywalls. So I built AuditMetric . The core platform gives you 3 free audits every single day , technical SEO audits, and unlimited CVE vulnerability checks to ensure your site is secure from",
  "url": "https://www.reddit.com/r/SideProject/comments/1udcqgr/i_built_auditmetric_a_free_website_auditor_with/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-23",
  "title_zh": "我開發了 AuditMetric：一個提供無限次 CVE 安全檢查的免費網站稽核工具，無月費訂閱。",
  "summary_zh": "嘿 r/SideProject，我受夠了網站稽核工具把基本的安全和健康掃描藏在昂貴的付費牆後面。所以我開發了 AuditMetric。這個核心平台每天提供 3 次免費稽核..."
 },
 {
  "title": "So I bought my own app for 13US. I was quite happy. Next time, it’ll be 10k. ))) Will it make me even happier,",
  "summary": "I was losing my motivation, so I paid myself $13 from my own SaaS today. A friend pitched in another $20 just to keep me from quitting. Total revenue: $33. It sounds minor, but after months of staring at server logs, debugging code, and building in a vacuum, seeing actual money move from my platform",
  "url": "https://www.reddit.com/r/SideProject/comments/1ua9tp6/so_i_bought_my_own_app_for_13us_i_was_quite_happy/",
  "source": "r/SideProject",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "所以我用 13 美元買了自己的應用程式。我非常開心。下次，會是 1 萬美元。))) 這會讓我更開心嗎，",
  "summary_zh": "我快失去動力了，所以我今天從我自己的 SaaS 支付了自己 13 美元。一個朋友又贊助了 20 美元，只是為了阻止我放棄。總營收：33 美元。這聽起來微不足道，但在盯著看了幾個月後..."
 },
 {
  "title": "What do you wish you knew before launching your first solo app?",
  "summary": "I’ve been building my first app alone for about a year now and I’m finally getting close to launching. No team, no funding, just me figuring it out as I go. Honestly it’s been humbling. I thought the hard part was building the thing. Turns out that’s maybe half of it. The other half is everything no",
  "url": "https://www.reddit.com/r/SideProject/comments/1udzwzx/what_do_you_wish_you_knew_before_launching_your/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-24",
  "title_zh": "在推出你的第一個獨立應用程式之前，你希望自己當初知道什麼？",
  "summary_zh": "我獨自開發我的第一個應用程式大約一年了，現在終於快要推出了。沒有團隊，沒有資金，就只有我一個人邊做邊摸索。老實說，這讓我學到很多。我原以為..."
 },
 {
  "title": "HTML Forms - Straight to Email (keep your side projects organized)",
  "summary": "Like most in this subreddit I create a ton of sites to gauge interest and with AI agents my increase in sites published per month has skyrocketed. The only annoying thing: setting up email for contact forms and keeping everything organized... So, I created https://html.contact/ 'Paste one URL into y",
  "url": "https://www.reddit.com/r/SideProject/comments/1uexqmu/html_forms_straight_to_email_keep_your_side/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-25",
  "title_zh": "HTML 表單 - 直接寄到電子郵件 (讓你的副業專案保持井然有序)",
  "summary_zh": "像這個 subreddit 的大多數人一樣，我會建立很多網站來測試市場反應，隨著 AI 代理的出現，我每月發布的網站數量更是暴增。唯一惱人的地方：設定聯絡用的電子郵件..."
 }
];
