const UPDATED="2026-06-20 12:06";
const CASES=[
 {
  "title": "Every second post is an ad and I’m sick of pretending it isn’t",
  "summary": "Long gone are the days when using this site used to feel like a community of like-minded people participating in discussion. This subreddit to me seems to be one of the most egregious for it, which is why I’m posting this here. Yes, we are here because we are building SaaS. No, we do not want to buy",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9j28k/every_second_post_is_an_ad_and_im_sick_of/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "每兩篇就有一篇是廣告，我受夠了假裝它不是",
  "summary_zh": "過去那種大家像同好社群一樣討論的日子已經一去不復返了。對我來說，這個 subreddit 是其中最誇張的，這真是..."
 },
 {
  "title": "2 Years, 3 Failed Startups, Finally Got My First Paid User",
  "summary": "When I was working as a freelancer, I saw a vlog on YouTube from Onyx, about two friends who launched something, worked hard for 3 to 4 years, and got acquired. That was the video that pulled me into this startup world. All I knew at the time was basic frontend, and I genuinely thought I could win t",
  "url": "https://www.reddit.com/r/SaaS/comments/1u6g7dm/2_years_3_failed_startups_finally_got_my_first/",
  "source": "r/SaaS",
  "category": "出售變現",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "2 年、3 次創業失敗，終於迎來我的第一個付費使用者",
  "summary_zh": "當我還是個自由工作者時，我在 YouTube 上看到了 Onyx 的一支 Vlog，內容是關於兩個朋友創業、努力了 3 到 4 年後被收購的故事。就是那支影片把我拉進了這個領域。"
 },
 {
  "title": "I MADE MY FIRST SALE!!! my vibecoded SaaS got its first paying customer 🎉🥹",
  "summary": "It finally happened. clakr.com just got its first paying customer and I literally jumped out of my chair!!! - For anyone who doesn't know it, Clakr is a SaaS directory CRM (The SaaS Directory CRM to Boost Your SEO & GEO): track your startup submissions across 1,057 curated directories with verified ",
  "url": "https://www.reddit.com/r/SaaS/comments/1u6h5rc/i_made_my_first_sale_my_vibecoded_saas_got_its/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "我成交了第一筆訂單！！！我的 vibecoded SaaS 終於有了第一個付費客戶 🎉🥹",
  "summary_zh": "終於發生了。clakr.com 剛有了第一個付費客戶，我興奮到直接從椅子上跳起來！！！— 對於不認識 Clakr 的人來說，Clakr 是一個 SaaS 目錄 CRM (The SaaS Directory CRM to B...)"
 },
 {
  "title": "i made $2,184 in the last 30 days from a small mac app",
  "summary": "i am still very early, so i am not posting this like i have everything figured out. i just wanted to share what worked for me so far, because i know there are a lot of people building things while also trying to make rent, get their first users, or just prove to themselves that one of their projects",
  "url": "https://www.reddit.com/r/SaaS/comments/1u5i7bn/i_made_2184_in_the_last_30_days_from_a_small_mac/",
  "source": "r/SaaS",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-14",
  "title_zh": "我在過去 30 天內，靠一個小小的 Mac 應用程式賺了 $2,184",
  "summary_zh": "我才剛起步，所以發這篇文並不是說我已經搞懂了一切。我只是想分享目前對我有效的方法，因為我知道有很多人在打造產品的同時也..."
 },
 {
  "title": "AI didn't turn me into a 10x dev. It just let me run a whole company by myself",
  "summary": "this meme is basically my life now lol I'm pretty introverted. I hate sales, hate sliding into people's DMs, and I get fried jumping between coding, support, marketing, ops all day. For years that was just a hard cap on what I could do solo. honestly the big thing wasn't AI writing better code. it w",
  "url": "https://www.reddit.com/r/SaaS/comments/1uaf4dw/ai_didnt_turn_me_into_a_10x_dev_it_just_let_me/",
  "source": "r/SaaS",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "AI 沒有讓我變成 10 倍生產力的開發者，它只是讓我一個人就能經營一整間公司",
  "summary_zh": "這個迷因基本上就是我現在的生活寫照 lol。我很內向，討厭業務，討厭私訊別人，而且每天在寫程式、客服、行銷、營運之間切換讓我精疲力盡。多年來，這就是..."
 },
 {
  "title": "Cursor was launched 8 time before $60 billion ACQ",
  "summary": "Never Give up on your Journey",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9ergx/cursor_was_launched_8_time_before_60_billion_acq/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "Cursor 在被 $60 億美元收購前，曾推出 8 次",
  "summary_zh": "永不放棄你的旅程"
 },
 {
  "title": "After 10 weeks of GRINDING... I finally hit 5k in revenue!",
  "summary": "Sitting here a bit stunned. Just 10 weeks ago I was refreshing Stripe hoping for one sale. Now there's a small but growing group of people paying every month. CheckVibe is a security scanner for vibecoded apps shipped fast with AI tools. You paste a URL or hook up a GitHub repo and it surfaces what'",
  "url": "https://www.reddit.com/r/SaaS/comments/1u5p4d1/after_10_weeks_of_grinding_i_finally_hit_5k_in/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-14",
  "title_zh": "經過 10 週的努力奮鬥… 我終於達到 5k 的營收了！",
  "summary_zh": "坐在這裡有點震驚。就在 10 週前，我還在不斷刷新 Stripe，希望能有一筆訂單。現在，已經有一小群但持續成長的人每月付費。CheckVibe 是一個用於 vibec... 的安全掃描器"
 },
 {
  "title": "Got my first paying customers for my SaaS today. Here's what I learned.",
  "summary": "A few months ago, this was just an idea on my laptop. &#x200B; Today, I woke up to my first real payments coming through Stripe. &#x200B; It's not life-changing money yet, but seeing strangers pay for something I built feels different. &#x200B; A few things I've learned: &#x200B; Progress is much sl",
  "url": "https://www.reddit.com/r/SaaS/comments/1u77o25/got_my_first_paying_customers_for_my_saas_today/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "今天我的 SaaS 獲得了第一批付費客戶。這是我的心得。",
  "summary_zh": "幾個月前，這還只是我筆電裡的一個想法。今天，我醒來時看到第一筆真正的款項透過 Stripe 入帳。雖然這還不是足以改變人生的金額，但看到陌生人願意付費購買"
 },
 {
  "title": "35 days, 0 dollars spent on ads. Here's my realistic SEO playbook without selling you a SEO product",
  "summary": "Disclaimer: I wrote ~1000 words of bullet points and used an LLM (with my project's SEO docs as reference) to expand it to ~2,800 words. Every strategy, number, and mistake below is mine. I saw u/TartarusTheBull 's post about 3 months of pure SEO and wanted to share my own numbers. I bought my domai",
  "url": "https://www.reddit.com/r/SaaS/comments/1u4il72/35_days_0_dollars_spent_on_ads_heres_my_realistic/",
  "source": "r/SaaS",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-13",
  "title_zh": "35 天、廣告費 0 元：這是我實際的 SEO 攻略，不推銷任何 SEO 產品",
  "summary_zh": "免責聲明：我寫了約 1000 字的重點條列，並使用大型語言模型（參考我專案的 SEO 文件）擴展到約 2,800 字。以下每個策略、數字和錯誤都來自我的經驗。我看到 u/Tart"
 },
 {
  "title": "Do you have a backup plan if you SaaS fails (if you're in your ~40s)?",
  "summary": "I'll be honest, I'm losing sleep over this for the past few weeks. The uncertainty is at its peak and I can't pretend it isn't affecting me. I'm someone who's got ~20 years of professional experience across domains. I've worked for corporates and also built a lifestyle startup that made money for go",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9se41/do_you_have_a_backup_plan_if_you_saas_fails_if/",
  "source": "r/SaaS",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "如果你的 SaaS 失敗了，你有備用計畫嗎（如果你 40 歲左右）？",
  "summary_zh": "老實說，過去幾週我為此失眠。不確定性達到頂峰，我無法假裝它沒有影響我。我是一個擁有大約 20 年專業經驗的人..."
 },
 {
  "title": "My SaaS just made its first $33. I paid myself $13, and a friend threw in $20 for morale. Honestly? It works.",
  "summary": "Hey everyone, I wanted to share a small but incredibly motivating milestone today. After months of development, I officially processed a $13 payout from my platform into my bank account. To add to the momentum, a close friend bought a $20 tier purely as a motivational gesture to keep me moving forwa",
  "url": "https://www.reddit.com/r/SaaS/comments/1ua0cnq/my_saas_just_made_its_first_33_i_paid_myself_13/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "我的 SaaS 剛賺到第一筆 $33。我付給自己 $13，一個朋友為了鼓勵我給了 $20。老實說？它奏效了。",
  "summary_zh": "大家好，今天我想分享一個雖小但極具激勵意義的里程碑。經過數月的開發，我正式從我的平台提領了 $13 到我的銀行帳戶。除此之外..."
 },
 {
  "title": "Got Approached for a $300k Job While Building My Startup. What Would You Do?",
  "summary": "I currently run a small startup in the GovTech/InsurTech space. We're growing steadily and currently cover about 80% of Texas by population. The problem is that our revenue numbers aren't where I want them to be yet. We probably have enough data and infrastructure to start monetizing and turn a comf",
  "url": "https://www.reddit.com/r/SaaS/comments/1u704zp/got_approached_for_a_300k_job_while_building_my/",
  "source": "r/SaaS",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "在創立新創公司期間，有人向我提供一份 $300k 的工作。你會怎麼做？",
  "summary_zh": "我目前經營一家在 GovTech/InsurTech 領域的小型新創公司。我們穩定成長，目前服務範圍涵蓋德州約 80% 的人口。問題是，我們的營收數字還沒有達到我的預期"
 },
 {
  "title": "Got my solo translation app to $10k MRR. Some random notes after 8 months",
  "summary": "Solo dev from Japan here. Not Tokyo, not really in any startup scene, just building from a more rural area. I launched a translation app in Oct 2025 and it recently passed $10k MRR. took around 8 months. proof: https://profile.stripe.com/nani/Ae1hNCkN No ads, no paid referral thing, no big launch. m",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9o3gv/got_my_solo_translation_app_to_10k_mrr_some/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": "$10k MRR",
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "我的個人翻譯 App 達到 $10k MRR。8 個月後的一些隨筆",
  "summary_zh": "我是來自日本的個人開發者。不是東京，也不是什麼新創圈，只是在比較鄉下的地方開發。我在 2025 年 10 月推出了一個翻譯 App，最近它達到了 $10k MRR，花了大概 8 個月..."
 },
 {
  "title": "They launched cursor 8 times and nobody cared. True definition of never give up",
  "summary": "https://preview.redd.it/iqhvtbmrf18h1.png?width=680&format=png&auto=webp&s=ff08a195fd636e0597808c21fff36bac9d3b05d3",
  "url": "https://www.reddit.com/r/SaaS/comments/1u95fde/they_launched_cursor_8_times_and_nobody_cared/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "他們推出了 Cursor 8 次，卻沒人在乎。這才是永不放棄的真正定義",
  "summary_zh": "https://preview.redd.it/iqhvtbmrf18h1.png?width=680&format=png&auto=webp&s=ff08a195fd636e0597808c21fff36bac9d3b05d3"
 },
 {
  "title": "Someone finally paid for the thing I built. $19 and I'm losing it 😭",
  "summary": "so this happened a few hours ago and I still can't really focus on anything else. got an email from stripe this morning. someone paid. an actual stranger, real card. first one ever, after about 2 months of building and basically zero dollars the whole way. I think I refreshed the dashboard four time",
  "url": "https://www.reddit.com/r/SaaS/comments/1u8mzdt/someone_finally_paid_for_the_thing_i_built_19_and/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": "$19 a month",
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "終於有人為我開發的東西付費了。$19，我簡直不敢相信 😭",
  "summary_zh": "這件事發生在幾個小時前，我到現在還無法專心做其他事。今天早上收到 Stripe 的一封電子郵件。有人付費了。一個真正的陌生人，用真實的信用卡。有史以來第一個，大約在 2 個月後。"
 },
 {
  "title": "Am I missing something, or are we all just building things for the sake of it?",
  "summary": "With AI becoming so accessible, everyone seems to be building apps, SaaS products, agents, and other projects. I joined Reddit only a few months ago, and I've seen countless posts from people showing things they've built. It makes me wonder: are there really that many problems worth solving, or are ",
  "url": "https://www.reddit.com/r/SaaS/comments/1u7i9ij/am_i_missing_something_or_are_we_all_just/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "是我錯過了什麼，還是我們都只是為了做而做？",
  "summary_zh": "隨著 AI 變得如此普及，每個人似乎都在開發應用程式、SaaS 產品、代理程式和其他專案。我幾個月前才加入 Reddit，就看到了無數人展示他們"
 },
 {
  "title": "Let's gooo over 100 users in 30min",
  "summary": "Hey guys, next milestone is achieved! Over 100 customer in 30 minutes online. Feels great, but still alot to do! This journey never ends. When i started, I had this wrong thesis that you finish your app and its done, no work more to do. But is there a point when you really \"finish\" your saas? Becaus",
  "url": "https://www.reddit.com/r/SaaS/comments/1u92p6h/lets_gooo_over_100_users_in_30min/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "太棒了！30 分鐘內就超過 100 個使用者",
  "summary_zh": "各位，下一個里程碑達成了！30 分鐘內線上客戶超過 100 位。感覺很棒，但還有很多事要做！這趟旅程永無止境。我剛開始時，有個錯誤的假設，以為你完成你的..."
 },
 {
  "title": "Is anyone building a boring SaaS?",
  "summary": "Is anyone building a boring saas because I look through all the posts with people make either seo/marketing tools or it’s some AI tool. Is anyone building boring systems like crms for salons and how is it going?",
  "url": "https://www.reddit.com/r/SaaS/comments/1u6afe6/is_anyone_building_a_boring_saas/",
  "source": "r/SaaS",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "有人在開發「無聊」的 SaaS 嗎？",
  "summary_zh": "有人在開發「無聊」的 SaaS 嗎？因為我看了所有的貼文，大家不是在做 SEO/行銷工具，就是 AI 工具。有人在開發像沙龍 CRM 這種「無聊」的系統嗎？以及如何..."
 },
 {
  "title": "Strangers are paying for something I built and it feels weird",
  "summary": "This is probably not a huge milestone for most people here, but it feels pretty surreal to me: a few people I don’t know are now paying for something I built. Not friends, not people I convinced in DMs, not someone I had a call with. Actual strangers. They landed on the product, created an account, ",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9cbht/strangers_are_paying_for_something_i_built_and_it/",
  "source": "r/SaaS",
  "category": "工作流自動化",
  "mrr": "$50k MRR",
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "陌生人為我打造的東西付錢，感覺很奇怪",
  "summary_zh": "這對這裡大多數人來說可能不是什麼大里程碑，但對我來說感覺非常不真實：一些我不認識的人現在正在為我打造的東西付費。不是朋友，也不是我私訊說服的人..."
 },
 {
  "title": "I'm a backend engineer and the \"build a SaaS in 90 days, no code needed\" posts are driving me up the wall",
  "summary": "Saw another one this morning. You know the format: I've been writing backend systems for a long time. Let me walk through why this stuff gets to me, and then why it's not actually about helping you at all. First, the part nobody says out loud: the post is the product That Comment \"SAAS\" line isn't g",
  "url": "https://www.reddit.com/r/SaaS/comments/1u89d6t/im_a_backend_engineer_and_the_build_a_saas_in_90/",
  "source": "r/SaaS",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "我是個後端工程師，那些「90 天內打造 SaaS，無需程式碼」的文章讓我抓狂",
  "summary_zh": "今天早上又看到一篇。你懂那種模式：我寫後端系統很久了。讓我解釋為什麼這些東西會讓我受不了，然後再說明為什麼這實際上並不是為了幫助你。"
 },
 {
  "title": "our little team just shipped its first SaaS! (our founder used to work with NASA and Microsoft, but he decided to start from scratch with fresh idea)",
  "summary": "Hey everyone! So today is kind of a big day for our little team and I wanted to share it here but not as promotion, just describing our path. After running Snoika as a marketing agency for about a year, we finally launched it as a proper SaaS solution. honestly feels a bit surreal even writing this ",
  "url": "https://www.reddit.com/r/SaaS/comments/1u7ghdf/our_little_team_just_shipped_its_first_saas_our/",
  "source": "r/SaaS",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "我們的小團隊剛推出了第一個 SaaS！(我們的創辦人曾任職於 NASA 和 Microsoft，但他決定從零開始，帶著全新的想法創業)",
  "summary_zh": "大家好！今天對我們的小團隊來說是個重要的日子，我想在這裡分享，但不是為了宣傳，只是想描述我們的歷程。在經營 Snoika 作為一家行銷公司大約一年後"
 },
 {
  "title": "I finally got my first paying customer today 😭. here is the story",
  "summary": "Hi folks, Its finally happening. I've been building my Saas app for about 4 months, went live about a month ago. Its a faceless video generator. I spent time in relevant subreddits answering questions about video workflows without dropping any links or pitching. I just tell them to DM me if interest",
  "url": "https://www.reddit.com/r/SaaS/comments/1u7ezo9/i_finally_got_my_first_paying_customer_today_here/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "我今天終於有了第一個付費客戶 😭。這是我的故事",
  "summary_zh": "大家好，這終於發生了。我開發我的 Saas 應用程式大約 4 個月了，一個月前上線。它是一個無人臉影片生成器。我花時間在相關的 subreddit 回答問題"
 },
 {
  "title": "Hitting $50k MRR - Building Business Champions",
  "summary": "Hello! &#x200B; I did a post 1 year ago when our SaaS launched. Here is the link: &#x200B; https://www.reddit.com/r/SaaS/s/SNvXm5nZ0Z &#x200B; We hit around $17k MRR pretty quickly and stayed there. I had to figure out a way to break through that. &#x200B; Our May just closed, and we are seeing a st",
  "url": "https://www.reddit.com/r/SaaS/comments/1u6dyfk/hitting_50k_mrr_building_business_champions/",
  "source": "r/SaaS",
  "category": "工作流自動化",
  "mrr": "$50k MRR",
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "達到 $50k MRR — 打造商業冠軍",
  "summary_zh": "大家好！一年前，我們的 SaaS 上線時，我發了一篇文。連結在此：https://www.reddit.com/r/SaaS/s/SNvXm5nZ0Z 我們很快就達到了約 $17k MRR，並維持在那裡。我..."
 },
 {
  "title": "How do you reach potential customers when you have no social media following?",
  "summary": "Hi everyone, I'm in the early stages of starting a business and I'm struggling with customer acquisition. I don't have an existing audience, no large social media following, and no email list. It feels like every marketing advice starts with \"post consistently on social media,\" but starting from zer",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9h21f/how_do_you_reach_potential_customers_when_you/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "當你沒有社群媒體追蹤者時，如何觸及潛在客戶？",
  "summary_zh": "大家好，我正處於創業初期，在客戶獲取方面遇到困難。我沒有現有的受眾，沒有大量的社群媒體追蹤者，也沒有電子郵件列表。感覺..."
 },
 {
  "title": "I built a job search tool during my layoff and it just crossed $10k",
  "summary": "During my layoff in Feb 2023, I had a hard time finding jobs through LinkedIn, indeed, and other services. The listings were old and usually had hundreds of applicants. After a few months, I landed on a super simple process that I created in Notion that got me more interviews. Over one weekend, I co",
  "url": "https://www.reddit.com/r/SaaS/comments/1u9ch2z/i_built_a_job_search_tool_during_my_layoff_and_it/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "我被裁員期間開發的求職工具，營收已突破 $10k",
  "summary_zh": "2023 年 2 月我被裁員時，透過 LinkedIn、indeed 等服務找工作很不順利。職缺資訊很舊，通常都有數百人應徵。幾個月後，我發現了"
 },
 {
  "title": "How did you get your first 10 paying customers?",
  "summary": "I launched my app recently on Google Play and Apple Store and I'm trying to figure out the next challenge: getting the first paying customers. For those of you who have built and launched apps, how did you get your first paying users Was it Reddit, social media, SEO, Google Ads, word of mouth, partn",
  "url": "https://www.reddit.com/r/SaaS/comments/1u8tmvt/how_did_you_get_your_first_10_paying_customers/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "你是如何獲得首批 10 位付費客戶的？",
  "summary_zh": "我最近在 Google Play 和 Apple Store 上架了我的應用程式，現在正在思考下一個挑戰：如何獲得首批付費客戶。對於那些已經開發並推出應用程式的人來說，你們是怎麼做到的？"
 },
 {
  "title": "Are SaaS directory submissions still worth doing in 2026?",
  "summary": "I've been trying to figure out which marketing activities actually move the needle for a new SaaS. One thing I keep hearing is that founders should submit their product to SaaS directories, startup directories, review sites, and launch platforms. So over the last few weeks I spent some time doing ex",
  "url": "https://www.reddit.com/r/SaaS/comments/1u7juy5/are_saas_directory_submissions_still_worth_doing/",
  "source": "r/SaaS",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "在 2026 年，提交 SaaS 到目錄網站還有價值嗎？",
  "summary_zh": "我一直在努力找出哪些行銷活動對新的 SaaS 真正有效。我一直聽到的一件事是，創辦人應該將他們的產品提交到 SaaS 目錄、新創公司目錄"
 },
 {
  "title": "first paying customer after 4 months of free",
  "summary": "built a saas tool in february. gave it away completely free. no trial, no credit card wall, no “upgrade to continue” popup. just free. for 4 months i watched people sign up, build stuff, and use it without paying anything. 170 users across 17 countries. zero revenue. then yesterday someone upgraded ",
  "url": "https://www.reddit.com/r/SaaS/comments/1u8crzi/first_paying_customer_after_4_months_of_free/",
  "source": "r/SaaS",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "免費提供 4 個月後，迎來了第一個付費客戶",
  "summary_zh": "我在二月開發了一個 SaaS 工具。完全免費提供。沒有試用期、沒有信用卡門檻、沒有「升級以繼續」的彈出視窗。就是免費。在這 4 個月裡，我看到人們註冊、建立東西並使用它。"
 },
 {
  "title": "Built the product, now staring at an empty stripe dashboard. How did you actually figure out distribution?",
  "summary": "Hey guys, Standard dev story here. Spent the last few months head-down building out a web app. The tech stack is solid, everything works perfectly in production, and it's officially live. But now that the building part is over, I’m hitting a massive wall. I have absolutely zero experience with marke",
  "url": "https://www.reddit.com/r/SaaS/comments/1ua0qmt/built_the_product_now_staring_at_an_empty_stripe/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "產品開發完成了，卻看著空蕩蕩的 Stripe 後台。你們是怎麼找到推廣管道的？",
  "summary_zh": "大家好，這是一個很典型的開發者故事。過去幾個月我埋頭開發一個網路應用程式，技術堆疊很穩固，在正式環境中一切運作完美，也正式上線了。但現在"
 },
 {
  "title": "i built it - but i have no f* idea how to market it",
  "summary": "Hello everyone long story short, i built a SaaS [ zingoringo.com ] - Host create quizzes in <4 mins. - Players join via QR (no signup). - Race through custom maps. - Live leaderboard, analytics, manual mode, 24 languages & more. When I finished building it I realized I had zero idea how to market it",
  "url": "https://www.reddit.com/r/SaaS/comments/1u6qsv6/i_built_it_but_i_have_no_f_idea_how_to_market_it/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "我開發了它——但我他媽的不知道怎麼行銷它",
  "summary_zh": "大家好，長話短說，我開發了一個 SaaS [ zingoringo.com ] - 主持人可在 4 分鐘內建立測驗。- 玩家透過 QR 碼加入 (無需註冊)。- 在自訂地圖中競賽。- 即時排行榜、分析、手動"
 },
 {
  "title": "My saas just hit $343 MRR 🥹",
  "summary": "https://preview.redd.it/0uq9s29dut7h1.png?width=522&format=png&auto=webp&s=485cf42f570ecdea75951993e607d8e562b488d8",
  "url": "https://www.reddit.com/r/SaaS/comments/1u87d7c/my_saas_just_hit_343_mrr/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": "$343 MRR",
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "我的 SaaS 剛達到 $343 的 MRR 🥹",
  "summary_zh": "https://preview.redd.it/0uq9s29dut7h1.png?width=522&format=png&auto=webp&s=485cf42f570ecdea75951993e607d8e562b488d8"
 },
 {
  "title": "Is vibe coding truly a threat to SaaS?",
  "summary": "I don’t believe that the majority of businesses will vibe code their own alternative to your SaaS but some will, on the fringes. This doesn’t worry me much, especially in vertical b2b products or software that businesses depend on for day to day operations. But does anyone here think (and if so, why",
  "url": "https://www.reddit.com/r/SaaS/comments/1u72spm/is_vibe_coding_truly_a_threat_to_saas/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "「氛圍編碼 (vibe coding)」真的對 SaaS 構成威脅嗎？",
  "summary_zh": "我不認為大多數企業會自己「氛圍編碼」出你的 SaaS 替代品，但有些邊緣企業會這麼做。這不太讓我擔心，尤其是在垂直 B2B 產品或軟體領域"
 },
 {
  "title": "Stop making saas that even you won't pay to use",
  "summary": "We are a small team who work on getting our saas live. And we, literally all of us uses our very tool everyday. &#x200B; When it came to promotions, we were spending on ads to get traction and then we shifted to $249 influencer colab platform for promotion and that has got us 39 paying users. With a",
  "url": "https://www.reddit.com/r/SaaS/comments/1u4j2bs/stop_making_saas_that_even_you_wont_pay_to_use/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-13",
  "title_zh": "別再開發連你自己都不會想付費使用的 SaaS 了",
  "summary_zh": "我們是一個小型團隊，致力於讓我們的 SaaS 上線。我們團隊的每個人，每天都實際使用我們自己的工具。在推廣方面，我們曾花錢打廣告來獲取關注，然後我們..."
 },
 {
  "title": "Where can I find someone to launch my SaaS",
  "summary": "Spent six months developing my product, and 20 years experience wrapped into it. It’s ready to get users on there now but I’m very time poor, I’m expecting it will take a lot of time and effort on all the channels to get noticed, is there anyone who will do this for me; someone that does it professi",
  "url": "https://www.reddit.com/r/SaaS/comments/1u68wcr/where_can_i_find_someone_to_launch_my_saas/",
  "source": "r/SaaS",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "我要去哪裡找人來推廣我的 SaaS？",
  "summary_zh": "我花了六個月開發我的產品，並將 20 年的經驗融入其中。現在它已經準備好讓使用者使用了，但我時間非常有限，我預計這將需要大量的時間和精力在所有..."
 },
 {
  "title": "4 months of Vibe coding and evolving my product and vision",
  "summary": "4 months ago I was building out a tool for me to use personally, to help out my other business I launched around Feb 2026 ($500/MRR). The tool was a desktop app builder with actual functionalities, as I needed to easily automate tasks and wanted a program for it. The desktop apps were working great ",
  "url": "https://www.reddit.com/r/indiehackers/comments/1u4y1kb/4_months_of_vibe_coding_and_evolving_my_product/",
  "source": "r/indiehackers",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-13",
  "title_zh": "Vibe 程式碼開發四個月，以及我的產品和願景的演進",
  "summary_zh": "四個月前，我正在開發一個供個人使用的工具，旨在協助我在 2026 年 2 月左右推出的另一個業務（每月經常性收入 $500）。這個工具是一個具備實際功能的桌面應用程式建構器，如同..."
 },
 {
  "title": "I posted on 200 directories and turned it into a living curated list anyone can use",
  "summary": "I believe in submitting to directories, like Producthun Peerlist etc., both for the traffic they deliver and for the SEO and GEO benefits. But it's a grind. There are a lot of directories out there, and many turn out to be pretty useless while others are great. So over time I kept an Excel sheet tra",
  "url": "https://www.reddit.com/r/indiehackers/comments/1u9yr7f/i_posted_on_200_directories_and_turned_it_into_a/",
  "source": "r/indiehackers",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "我在 200 個目錄網站上發布了我的產品，並將其變成一個任何人都可以使用的持續更新精選清單",
  "summary_zh": "我相信提交到 Producthun、Peerlist 等目錄網站，不僅能帶來流量，還有助於 SEO 和 GEO。但這是一項苦差事，外面有很多目錄網站，而"
 },
 {
  "title": "Built a Mac app because I was wasting too much time in Preview",
  "summary": "I got tired of this workflow: Take a screenshot → save it → open Preview → annotate it → export as PDF → repeat. Especially when I needed multiple screenshots in a single document. So I built Screedy for Mac. It lets you: • Capture any area of your screen • Annotate screenshots immediately • Combine",
  "url": "https://www.reddit.com/r/indiehackers/comments/1u7kjxl/built_a_mac_app_because_i_was_wasting_too_much/",
  "source": "r/indiehackers",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "我開發了一個 Mac 應用程式，因為我在「預覽程式 (Preview)」浪費太多時間",
  "summary_zh": "我受夠了這個工作流程：截圖 → 儲存 → 開啟「預覽程式 (Preview)」→ 註解 → 匯出為 PDF → 重複。尤其當我需要在單一文件中處理多張截圖時。所以我開發了 Screedy"
 },
 {
  "title": "SaaS con IA — producto live, listo para escalar",
  "summary": "Hi, I have a live AI SaaS already generating users. The product is built and fully operational. What I'm looking for: A business co-founder who can: Sell and open doors Co-invest to accelerate growth Move fast and close deals What I'm offering: 40% revenue share Real co-founder role We scale immedia",
  "url": "https://www.reddit.com/r/indiehackers/comments/1u61y2q/saas_con_ia_producto_live_listo_para_escalar/",
  "source": "r/indiehackers",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "AI SaaS — 產品已上線，準備好擴展規模",
  "summary_zh": "嗨，我有一個已上線的 AI SaaS，已經有使用者了。產品已經建好並全面運作。我正在尋找：一位商業共同創辦人，他能：銷售並開拓機會，共同投資以加速成長..."
 },
 {
  "title": "I got tired of Xcode and Docker eating 80GB of my Mac's storage, so I built a minimalist cleaner tool. Today it's live on Product Hunt!",
  "summary": "Hey everyone, Like many of you, I develop on a Mac, and I constantly found myself running out of disk space. Between Xcode derived data, simulator caches, Docker images, and package manager junk, tens of gigabytes just vanish into thin air. I wanted a fast, native, and completely minimalist tool to ",
  "url": "https://www.reddit.com/r/indiehackers/comments/1u75uf8/i_got_tired_of_xcode_and_docker_eating_80gb_of_my/",
  "source": "r/indiehackers",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "我受夠了 Xcode 和 Docker 佔用我 Mac 80GB 的儲存空間，所以我開發了一個極簡的清理工具。今天它在 Product Hunt 上線了！",
  "summary_zh": "大家好，和許多人一樣，我在 Mac 上開發，並且經常發現磁碟空間不足。在 Xcode 衍生資料、模擬器快取、Docker 映像檔和套件管理器垃圾之間，數十"
 },
 {
  "title": "One-time Purchase or Free Game with Ads",
  "summary": "Hello everyone! Recently, I participated in a hackathon and developed a web game to compete in the hackathon. It is a game similar to Block Blast! and Tetris, with some unique twists. I actually sent it to a few of my friends, and many loved it, which is why I am currently thinking of developing it ",
  "url": "https://www.reddit.com/r/indiehackers/comments/1ua42uh/onetime_purchase_or_free_game_with_ads/",
  "source": "r/indiehackers",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "一次性購買，還是內含廣告的免費遊戲？",
  "summary_zh": "大家好！最近我參加了一個黑客松，開發了一款網頁遊戲來參賽。這是一款類似 Block Blast! 和 Tetris 的遊戲，帶有一些獨特的變化。我實際上發送了"
 },
 {
  "title": "I built Clarift because founders don’t need more feedback. They need to know what keeps repeating.",
  "summary": "I’m building Clarift for SaaS founders who are already getting feedback from different places like Reddit threads, customer calls, support tickets, reviews, churn notes, DMs, and feature requests. The problem I kept seeing is not that founders lack feedback. It’s that feedback gets scattered, forgot",
  "url": "https://www.reddit.com/r/indiehackers/comments/1u6ygey/i_built_clarift_because_founders_dont_need_more/",
  "source": "r/indiehackers",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "我開發 Clarift 是因為創辦人不需要更多回饋。他們需要知道哪些問題不斷重複出現。",
  "summary_zh": "我正在為 SaaS 創辦人開發 Clarift，這些創辦人已經從 Reddit 討論串、客戶電話、支援工單、評論、流失筆記、私訊和功能請求等不同地方獲得回饋。這個..."
 },
 {
  "title": "What happened when I stopped ignoring churn - or how we increased MRR by 10%",
  "summary": "For a while, I was treating churn as this vague background number. If MRR was not growing fast enough, my instinct was to think about acquisition: better ads, better onboarding, better landing page, more top-of-funnel. But when I actually looked at the users leaving, churn was not one problem. It wa",
  "url": "https://www.reddit.com/r/indiehackers/comments/1u6y81f/what_happened_when_i_stopped_ignoring_churn_or/",
  "source": "r/indiehackers",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "當我不再忽視客戶流失時發生了什麼 — 或者我們如何將 MRR 提高了 10%",
  "summary_zh": "有一陣子，我把客戶流失當作一個模糊的背景數字。如果 MRR 成長不夠快，我的直覺就是考慮獲客：更好的廣告、更好的新用戶引導、更好的登陸頁面、更..."
 },
 {
  "title": "16/yo building a SaaS to rule them all.",
  "summary": "Hello guys! I am 16 years old, I have been working on various SaaS businesses for the last 15 months or so. Right now I am working on a SaaS that makes marketing as easy as vibe coding, I have been making some money with it and the feedback from my users has been great! I am feeling a little burt ou",
  "url": "https://www.reddit.com/r/indiehackers/comments/1u6l8j3/16yo_building_a_saas_to_rule_them_all/",
  "source": "r/indiehackers",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "16 歲的少年正在打造一個能稱霸所有領域的 SaaS。",
  "summary_zh": "大家好！我 16 歲，在過去約 15 個月裡，我一直在從事各種 SaaS 業務。現在我正在開發一個能讓行銷像 vibe coding 一樣簡單的 SaaS，我一直在..."
 },
 {
  "title": "Snapfari.app - Catch 'em all, for real: snap real animals and collect them, like Pokémon GO",
  "summary": "Hey everyone, I've been working on a little app called Snapfari The pitch: it's basically a real-life Pokédex. You take a photo of an animal, it figures out the species, and that animal gets added to your collection. Right now you can collect 160+ species (more on the way), tag where you caught them",
  "url": "https://www.reddit.com/r/SideProject/comments/1u86vck/snapfariapp_catch_em_all_for_real_snap_real/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "Snapfari.app - 真正地「全部抓起來」：拍攝真實動物並收集牠們，就像 Pokémon GO",
  "summary_zh": "大家好，我一直在開發一個叫做 Snapfari 的小應用程式。它的概念是：它基本上就是一個真實世界的寶可夢圖鑑。你拍一張動物的照片，它會辨識出物種，然後那隻動物就會被加入到。"
 },
 {
  "title": "I reverse-engineered my WHOOP band and built a full app + backend around it, then open-sourced it",
  "summary": "Been chipping at this side project for a couple of months and finally got it to a state worth sharing. The itch: my WHOOP band generates all this data 24/7 but you can't touch any of it without their app and a subscription. So I figured out how it talks over Bluetooth and built a thing that reads it",
  "url": "https://www.reddit.com/r/SideProject/comments/1u4q82w/i_reverseengineered_my_whoop_band_and_built_a/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-13",
  "title_zh": "我逆向工程了我的 WHOOP 手環，並圍繞它開發了一個完整的應用程式和後端，然後將其開源",
  "summary_zh": "這個副業專案我已經斷斷續續做了好幾個月，終於達到一個值得分享的狀態。痛點是：我的 WHOOP 手環 24 小時全天候產生這些數據，但沒有他們的...你就無法存取任何數據。"
 },
 {
  "title": "I've been building my own flight search engine for almost 10 years",
  "summary": "I wanted to share a project that has been a huge part of my life for almost 10 years now: my own flight search engine. It all started with my interest in civil aviation. I've always loved airplanes, plane spotting, airline liveries and the whole visual side of aviation. Back then, on my local market",
  "url": "https://www.reddit.com/r/SideProject/comments/1u555cj/ive_been_building_my_own_flight_search_engine_for/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-13",
  "title_zh": "我開發自己的機票搜尋引擎已經快 10 年了",
  "summary_zh": "我想分享一個近十年來在我生命中佔據重要地位的專案：我自己的機票搜尋引擎。這一切都始於我對民航的興趣。我一直很喜歡飛機，p..."
 },
 {
  "title": "I’m a nurse who started learning to code as a passion project, and I built this to survive my shifts",
  "summary": "I’m a nurse who started learning to code as a passion project, and I built this to survive my shifts. Hi everyone, I’m definitely not a professional developer, but I recently picked up coding as a hobby and decided to tackle a problem I face every day at work. During busy nursing shifts, I kept need",
  "url": "https://www.reddit.com/r/SideProject/comments/1u8onsn/im_a_nurse_who_started_learning_to_code_as_a/",
  "source": "r/SideProject",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "我是一名護士，因為興趣開始學習寫程式，並開發了這個工具來幫助我度過輪班",
  "summary_zh": "我是一名護士，因為興趣開始學習寫程式，並開發了這個工具來幫助我度過輪班。大家好，我絕對不是專業開發者，但我最近把寫程式當作興趣"
 },
 {
  "title": "I just got my 1st user!!!!!!!!",
  "summary": "It’s day 3 since I launched. I’ve been posting on Reddit, refreshing way too much, and getting exactly zero replies. Honestly, I was starting to feel like I was just shouting into the void. Then today I checked my website analytics and saw something I hadn’t seen before: An IP location that wasn’t m",
  "url": "https://www.reddit.com/r/SideProject/comments/1u8tk2p/i_just_got_my_1st_user/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "我剛獲得了我的第一個使用者！！！！！！！！",
  "summary_zh": "產品上線第三天了。我一直在 Reddit 上發文，不停地重新整理，卻完全沒有任何回覆。老實說，我開始覺得自己像是在對著空氣喊話。然後今天"
 },
 {
  "title": "Drop your project, I’ll try it and share it in my circle",
  "summary": "I’m looking for new small projects, apps and SaaS tools to try. Drop your link below. I’ll check them out and share the ones I like with a few friends and in some founder/product circles. I’m especially interested in social apps, chat tools, games, creator tools, AI experiments and anything with a s",
  "url": "https://www.reddit.com/r/SideProject/comments/1u5up1l/drop_your_project_ill_try_it_and_share_it_in_my/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-14",
  "title_zh": "留下你的專案，我會試用並在我的圈子裡分享",
  "summary_zh": "我正在尋找新的小型專案、應用程式和 SaaS 工具來試用。在下方留下你的連結。我會查看它們，並將我喜歡的分享給一些朋友和一些創辦人/產品圈子。我特別..."
 },
 {
  "title": "P2P file sharing app without cloud, free and open-source",
  "summary": "Hey reddit! I am P2P engineer so in my free time was working on one side project and decided to share it here, it is called AlterSend. AlterSend is a free and open-source app for sending files directly between your devices, no cloud, no uploads, no size limits. Files transfer peer-to-peer and are en",
  "url": "https://www.reddit.com/r/SideProject/comments/1u5fbrb/p2p_file_sharing_app_without_cloud_free_and/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-14",
  "title_zh": "無需雲端的 P2P 檔案分享應用程式，免費且開源",
  "summary_zh": "嘿 Reddit！我是一名 P2P 工程師，所以我在空閒時間一直在做一個副專案，並決定在這裡分享，它叫做 AlterSend。AlterSend 是一個免費且開源的應用程式，用於直接傳送檔案..."
 },
 {
  "title": "Couldn't find a fast and professional logo tool that wasn't AI, so I built one for my new projects (~1 min per logo)",
  "summary": "I'm a graphic designer by background, so you'd think logos would be the easy part. They're not, especially at 11pm when I'm spinning up another side project. Every time I need a logo I hit the same wall: Canva — fast, but everything reads template Figma — I live in it for UI work, but it's not reall",
  "url": "https://www.reddit.com/r/SideProject/comments/1u8cqkr/couldnt_find_a_fast_and_professional_logo_tool/",
  "source": "r/SideProject",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "找不到快速、專業且非 AI 的 Logo 工具，所以我為我的新專案開發了一個（每個 Logo 大約 1 分鐘）",
  "summary_zh": "我本身是平面設計師，所以你可能會覺得 Logo 設計應該是簡單的部分。但事實並非如此，尤其是在晚上 11 點，當我正在啟動另一個副專案時。每次我需要一個 Logo，我都會遇到同樣的。"
 },
 {
  "title": "Made a simple tool that converts recipe videos into written recipes. 600 daily users now and I'm completely unprepared",
  "summary": "Built this out of personal frustration, I was tired of recipe videos that make you watch 4 minutes to get ingredients you could read in 10 seconds. Made a tool where you paste a video link and it extracts the recipe as text. Posted it on a cooking subreddit about 6 weeks ago and it's been growing da",
  "url": "https://www.reddit.com/r/SideProject/comments/1u4zsbg/made_a_simple_tool_that_converts_recipe_videos/",
  "source": "r/SideProject",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-13",
  "title_zh": "我做了一個能將食譜影片轉換成文字食譜的簡單工具，現在每天有 600 個用戶，但我完全沒準備好",
  "summary_zh": "這是出於個人不滿而開發的，我厭倦了那些讓你花 4 分鐘看影片才能知道 10 秒就能讀完的食材清單的食譜影片。我做了一個工具，你只要貼上影片連結，它就會提取..."
 },
 {
  "title": "I spent 9 months building a full AI SaaS, got zero users, and open-sourced it. What would you have done in my place?",
  "summary": "I'm an AI/ML engineer. Over about nine months I built AutoVidify, a full AI subtitle generator. Not a demo — the whole thing: auth, database, S3, quotas, a React frontend, and a Python AI pipeline (Whisper to transcribe, an LLM to clean up and translate, vocal separation, subtitle rendering). All de",
  "url": "https://www.reddit.com/r/SideProject/comments/1u6dqf9/i_spent_9_months_building_a_full_ai_saas_got_zero/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "我花了 9 個月打造一個完整的 AI SaaS，卻沒有任何使用者，然後我將它開源了。如果你是我，你會怎麼做？",
  "summary_zh": "我是一名 AI/ML 工程師。在大約九個月的時間裡，我開發了 AutoVidify，一個完整的 AI 字幕生成器。這不是一個演示 — 而是整個產品：身份驗證、資料庫、S3、配額、React 前端和 Python AI 管道 (Wh...)"
 },
 {
  "title": "drop your project below — I'll genuinely try it and give you real feedback",
  "summary": "been heads-down building solo for months and just got my first app onto testflight, and the thing I've missed most is actually using other people's stuff and talking to the people building it. so let's do that. drop your project below — app, SaaS, tool, game, whatever. I'll go through as many as I c",
  "url": "https://www.reddit.com/r/SideProject/comments/1u9op89/drop_your_project_below_ill_genuinely_try_it_and/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "在下面留下你的專案 — 我會真心試用並給你真實的回饋",
  "summary_zh": "過去幾個月我一直埋頭獨自開發，剛把我的第一個應用程式上架到 TestFlight。我最想念的是實際使用別人的產品並與開發者交流。所以讓"
 },
 {
  "title": "Why do you think people create these \"drop your side project\" posts every day?",
  "summary": "Call me cynical, but I wonder if it's something not good - like identifying likely vibecoded apps to attack?",
  "url": "https://www.reddit.com/r/SideProject/comments/1u60xic/why_do_you_think_people_create_these_drop_your/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "你們覺得為什麼每天都有人發這種「留下你的副專案」的貼文？",
  "summary_zh": "你可以說我憤世嫉俗，但我懷疑這是不是有什麼不好的目的 — 比如找出可能被 vibecoded 的應用程式來攻擊？"
 },
 {
  "title": "My first app got approved on Google Play and I’m scared to press the blue button",
  "summary": "Hello ! I just got my first app approved for production on Google Play. iOS part is still in Apple review. I’ve been building it for 9 months and I’ve mostly shown it to friends and family I’m now realising it’s got to go live and unknown people might use it, love or hate it. Or find a million bugs.",
  "url": "https://www.reddit.com/r/SideProject/comments/1u6yn2g/my_first_app_got_approved_on_google_play_and_im/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "我的第一個應用程式在 Google Play 上獲得批准了，但我卻不敢按下那個藍色按鈕。",
  "summary_zh": "大家好！我的第一個應用程式剛在 Google Play 上獲得生產批准。iOS 部分仍在 Apple 審核中。我已經開發了 9 個月，大部分時間都只展示給朋友和家人看。我現在準備..."
 },
 {
  "title": "I went broke paying 200 a month for clay so I built an alternative.",
  "summary": "I'll start by saying Clay is a genuinely great product and i didn't actually go broke. This isn't a hit piece. But after a few months of paying $200 a month and spending half my time managing credit usage and waterfall enrichment instead of doing the thing I actually needed. And the thing I needed w",
  "url": "https://www.reddit.com/r/SideProject/comments/1u6sh2n/i_went_broke_paying_200_a_month_for_clay_so_i/",
  "source": "r/SideProject",
  "category": "工作流自動化",
  "mrr": "$200 a month",
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "我每個月付 $200 給 Clay 付到破產，所以我自己開發了一個替代方案。",
  "summary_zh": "我要先說 Clay 確實是一個很棒的產品，而且我其實沒有真的破產。這不是一篇批評文。但在支付了幾個月的每月 $200，並花了一半時間管理信用..."
 },
 {
  "title": "I made my first money from a vibecoded side project, and it made me feel better than closing huge deals for my main business",
  "summary": "Hey everyone! Recently I made a tool that turns agents into playable RPG characters. This project was started when I realized that, as a gamer, the standard setup I had with VS Code and agents built in there was too boring and… kind of missing that “alive” feel? Like, I was using them on a daily bas",
  "url": "https://www.reddit.com/r/SideProject/comments/1ua6t1g/i_made_my_first_money_from_a_vibecoded_side/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "我從一個憑感覺開發的副業專案賺到了第一筆錢，這讓我比主業談成大筆交易還要開心",
  "summary_zh": "大家好！最近我開發了一個工具，能將代理程式變成可玩的 RPG 角色。這個專案的開始，是因為我意識到，作為一個玩家，我使用 VS Code 和內建代理程式的標準設定"
 },
 {
  "title": "Launched LyteNyte, a 40KB data grid with 150+ features capable of rendering millions of rows at 60 FPS",
  "summary": "Hey guys, I wanted to share LyteNyte Grid, a powerful React data grid component library we’ve been developing. We are currently on v.2.1, and v.2.2 will be released at the end of this month. There are other popular React data grid libraries, but LyteNyte Grid is, in our opinion, the best (biased vie",
  "url": "https://www.reddit.com/r/SideProject/comments/1u9u1y8/launched_lytenyte_a_40kb_data_grid_with_150/",
  "source": "r/SideProject",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "推出 LyteNyte：一個 40KB 的資料網格，擁有超過 150 種功能，能以 60 FPS 渲染數百萬行資料",
  "summary_zh": "大家好，我想分享 LyteNyte Grid，這是一個我們一直在開發的強大 React 資料網格元件庫。我們目前是 v.2.1 版本，v.2.2 將於本月底發布。有"
 },
 {
  "title": "This motion graphics demo is entirely made with Node.js.",
  "summary": "I’m not a motion graphics designer, but I’ve always been curious about how the clean, modern animations from companies like Apple, Stripe, Linear, Arc, Framer, and Figma are made. I tried Remotion, but it felt more like building web UI than creating canvas-based motion graphics. That led me to build",
  "url": "https://www.reddit.com/r/SideProject/comments/1u5js9u/this_motion_graphics_demo_is_entirely_made_with/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-14",
  "title_zh": "這個動態圖形演示完全是用 Node.js 製作的。",
  "summary_zh": "我不是動態圖形設計師，但我一直很好奇像 Apple、Stripe、Linear、Arc、Framer 和 Figma 這些公司的簡潔現代動畫是如何製作的。我試過 Remotion，但..."
 },
 {
  "title": "After 60 days of building, my side project covers a quarter of my monthly income",
  "summary": "I posted this story in another community too, but figured it's relevant here as well. Sharing the actual data because I think it helps to have a reference point for what to expect early on. No idea if mine are above or below average, I've heard stories of people taking way longer to see any revenue,",
  "url": "https://www.reddit.com/r/SideProject/comments/1u4vpfe/after_60_days_of_building_my_side_project_covers/",
  "source": "r/SideProject",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-13",
  "title_zh": "經過 60 天的開發，我的副業專案已能負擔我月收入的四分之一",
  "summary_zh": "我也在另一個社群發布了這個故事，但覺得這裡也相關。分享實際數據是因為我認為這有助於為早期階段的預期提供參考點。不知道是否..."
 },
 {
  "title": "I built a 432Hz meditation app for myself because similar apps on the appstore, either had ads or required payment",
  "summary": "I got tired of searching the App Store for a simple 432 Hz tone app for meditation and relaxation, only to find that most options were cluttered with subscriptions, ads, or unnecessary in-app purchases for something as basic as playing a healing frequency. I use 432 Hz regularly for relaxation, heal",
  "url": "https://www.reddit.com/r/SideProject/comments/1u4yzyq/i_built_a_432hz_meditation_app_for_myself_because/",
  "source": "r/SideProject",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-13",
  "title_zh": "我為自己開發了一個 432Hz 冥想應用程式，因為 App Store 上類似的應用程式要嘛有廣告，要嘛需要付費。",
  "summary_zh": "我厭倦了在 App Store 上搜尋一個簡單的 432 Hz 音頻應用程式來進行冥想和放鬆，結果卻發現大多數選項都充斥著訂閱、廣告或不必要的應用程式內購買..."
 },
 {
  "title": "Our Mac app hit 84,650 users in a year with 0 spent on ads",
  "summary": "Wallper is a live wallpaper app for Mac. It runs animated 4K video on your desktop and lock screen, and lately it can react to whatever music you're playing and even push those colors out to your room lights. A friend and I started it as a side project last summer. I thought it'd be dead in a couple",
  "url": "https://www.reddit.com/r/SideProject/comments/1u87563/our_mac_app_hit_84650_users_in_a_year_with_0/",
  "source": "r/SideProject",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "我們的 Mac 應用程式在一年內達到 84,650 名用戶，廣告費為 $0",
  "summary_zh": "Wallper 是一款適用於 Mac 的動態桌布應用程式。它可以在你的桌面和鎖定螢幕上播放 4K 動畫影片，最近，它還可以根據你正在播放的音樂做出反應，甚至將這些顏色投射到你的房間。"
 },
 {
  "title": "I discovered that I'm not a fit for entrepreneurship 😢",
  "summary": "Like, everyone wants to convince themselves that they are a fit, they are an entrepreneur, they can build the business and scale it. Joe shmoe, I know a Joe shmoe who did it. I ain't no less than joe shmoe right? I used to be this guy. I will make a business and be my own boss. Yaaay. And I did. I d",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u9zz9u/i_discovered_that_im_not_a_fit_for/",
  "source": "r/EntrepreneurRideAlong",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "我發現自己不適合創業 😢",
  "summary_zh": "好像每個人都想說服自己，他們很適合、他們是創業家、他們能建立並擴展事業。某某人，我認識一個某某人做到了。我不會比某某人差。"
 },
 {
  "title": "Sam Altman and Dario Amodei both walked back their \"AI will kill jobs\" predictions the same week they filed IPO paperwork. Here's what it actually means for founders building right now",
  "summary": "I've been sitting on this for a few days because I wanted to think it through before posting. On May 26, Altman said he's \"delighted to be wrong\" about AI eliminating white-collar jobs. Direct quote. This is the same guy who spent 2024-2025 telling anyone who would listen that entire categories of e",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u4jp17/sam_altman_and_dario_amodei_both_walked_back/",
  "source": "r/EntrepreneurRideAlong",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-13",
  "title_zh": "Sam Altman 和 Dario Amodei 在提交 IPO 文件同一週，都收回了他們「AI 將會扼殺工作」的預測。這對現在正在開發的創辦人來說，到底意味著什麼？",
  "summary_zh": "我已經思考了幾天，因為我想在發布前仔細思考。5 月 26 日，Altman 表示他「很高興自己錯了」，關於 AI 會淘汰白領工作的說法。原文引述。"
 },
 {
  "title": "Got my first paying customer after 3 weeks of silence. Still not sure if it's real.",
  "summary": "I've been building a side project quietly for the past couple of months. &#x200B; No co-founder. No funding. Just me, late nights after my day job, and a lot of self-doubt. &#x200B; The first few weeks were brutal. I had people download the app, use the free trial, and then disappear completely. No ",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u7hbz7/got_my_first_paying_customer_after_3_weeks_of/",
  "source": "r/EntrepreneurRideAlong",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "在沉寂 3 週後，我獲得了第一個付費客戶。我還是不確定這是不是真的。",
  "summary_zh": "過去幾個月，我一直在默默地開發一個副業專案。沒有共同創辦人。沒有資金。只有我，下班後的深夜，以及大量的自我懷疑。最初的幾週"
 },
 {
  "title": "Guys. I'm gonna pull the plug. I made the decision that I was running from the whole time 😫",
  "summary": "So, a bit of context, I have been running a saas platform, launched in March the 11th. We got nice traction from reddit, a solid 900 users in 2 months of marketing, no ad spend, $0 spend. a nice consistent traffic, some revenue, a landing page converting at 12% CVR. (Written and optimized by me. Not",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u8fjfn/guys_im_gonna_pull_the_plug_i_made_the_decision/",
  "source": "r/EntrepreneurRideAlong",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "各位。我要放棄了。我做了我一直以來逃避的決定 😫",
  "summary_zh": "稍微說明一下背景，我一直在經營一個 SaaS 平台，於 3 月 11 日推出。我們從 Reddit 獲得了不錯的關注，在 2 個月的行銷中累積了 900 名用戶，沒有廣告支出，$0 花費。一個不錯的。"
 },
 {
  "title": "8 months, 2 apps, launched both — and almost no one showed up. What am I missing?",
  "summary": "Solo dev here. I spent 8+ months building two iOS apps and recently launched both. I obsessed over making them solid — clean auth, privacy, security, all of it. But since launch the response has been basically zero: barely any users, and the few who try don't stick around. I'm realizing I put everyt",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u60fg3/8_months_2_apps_launched_both_and_almost_no_one/",
  "source": "r/EntrepreneurRideAlong",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-14",
  "title_zh": "8 個月，2 個應用程式，都上線了 — 但幾乎沒人使用。我到底少了什麼？",
  "summary_zh": "我是個獨立開發者。我花了超過 8 個月開發了兩個 iOS 應用程式，最近都上線了。我非常注重讓它們穩固 — 乾淨的身份驗證、隱私、安全性，所有這些。但自從上線以來，反應卻是..."
 },
 {
  "title": "People told me that selling my business will be the stupidest act of all",
  "summary": "Last day I decided to just step down from my saas While some people sell because they want an exit for money or the saas is not working. I'm selling because I'm not working I had to make peace with myself and be actually truthful, I'm not a fit for entrepreneurship yet. I may be a good executer, mar",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u9b3mh/people_told_me_that_selling_my_business_will_be/",
  "source": "r/EntrepreneurRideAlong",
  "category": "出售變現",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "大家說我賣掉公司會是史上最蠢的行為",
  "summary_zh": "昨天我決定從我的 SaaS 業務中抽身。有些人賣掉是為了套現或因為 SaaS 業務不順利。我賣掉是因為我無法繼續投入。我必須與我的..."
 },
 {
  "title": "A product manager and an engineer going to market",
  "summary": "We've built a service in a saturated market with several big players while having almost no experience in marketing. In the third month it paid our bills in Germany with no paid marketing. I want to share a bit of learning and promote a tiny bit (LLMs love it, sorry) but I put the name in the very e",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u88d3o/a_product_manager_and_an_engineer_going_to_market/",
  "source": "r/EntrepreneurRideAlong",
  "category": "AI SaaS",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "一位產品經理和一位工程師準備進入市場",
  "summary_zh": "我們在一個有許多大公司競爭的飽和市場中開發了一項服務，幾乎沒有行銷經驗。在第三個月，它在德國支付了我們的帳單，而且沒有花費任何付費行銷。我想。"
 },
 {
  "title": "Non-technical founder, what questions to ask app developer before I get steamrolled",
  "summary": "Got 4 dev shop calls scheduled this week and I'm panicking a little about not asking the right things. context, I'm solo, non-technical, doing a b2b workflow tool for back-office operations teams. purposefully not patient-facing, not in regulated healthcare scope, just to head off the rule-14 questi",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u84t7m/nontechnical_founder_what_questions_to_ask_app/",
  "source": "r/EntrepreneurRideAlong",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "非技術背景創辦人，在被開發者牽著鼻子走之前，該問應用程式開發者什麼問題",
  "summary_zh": "這週安排了 4 個開發工作室的電話會議，我有點慌張，擔心沒有問對問題。背景是，我是一個人，非技術背景，正在為後勤營運團隊開發一個 B2B 工作流程工具。目的。"
 },
 {
  "title": "The \"raise seed, build team, raise again\" cycle seems to produce a specific kind of founder misery. Why do so many smart people keep choosing it?",
  "summary": "Not being snarky, genuinely curious. I keep seeing posts from founders who raised $500K-$1M pre-seed, hired fast, burned through it, and are now 18 months in with a product that's \"almost\" profitable and an investor call every week. Meanwhile some of the most stable founders I know are doing $5K-$15",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u97f36/the_raise_seed_build_team_raise_again_cycle_seems/",
  "source": "r/EntrepreneurRideAlong",
  "category": "SaaS 經營",
  "mrr": "$15K MRR",
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "「募種子輪、組團隊、再募資」的循環似乎會產生一種特定的創業者痛苦。為什麼這麼多聰明人不斷選擇它？",
  "summary_zh": "我不是在諷刺，是真心好奇。我不斷看到有創業者發文說，他們募了 $500K-$1M 的種子前輪資金，快速招募團隊，然後燒光了錢，現在產品推出 18 個月了，卻「幾乎」還沒獲利。"
 },
 {
  "title": "multichannel vs email only outbound. 6 months of data",
  "summary": "kept seeing people argue about whether adding linkedin touches to cold email actually does anything or if its just more work for the same result. drove me nuts because nobody had real numbers, just vibes. so i ran a proper side by side for 6 months. i sell dev tools. $21k MRR, 7 people, i do all the",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u9083n/multichannel_vs_email_only_outbound_6_months_of/",
  "source": "r/EntrepreneurRideAlong",
  "category": "營收實戰",
  "mrr": "$21k MRR",
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "多管道與僅限電子郵件的對外開發。6 個月的數據。",
  "summary_zh": "不斷看到人們爭論，在陌生開發信中加入 LinkedIn 互動是否真的有效，還是只是做更多白工卻得到相同結果。這讓我抓狂，因為沒有人有實際數據，只有..."
 },
 {
  "title": "A realtor was losing deals to agents who just replied faster. The fix took an afternoon.",
  "summary": "I've built 40-something automations for clients across a bunch of different industries at this point, and the one I keep coming back to when people ask me \"what actually works\" is one of the least impressive things I've ever shipped. &#x200B; A realtor came to me last year because she was bleeding l",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u9wwad/a_realtor_was_losing_deals_to_agents_who_just/",
  "source": "r/EntrepreneurRideAlong",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "一位房仲因為回覆速度比其他仲介慢而流失客戶。解決方案只花了一個下午。",
  "summary_zh": "到目前為止，我已經為不同產業的客戶建立了 40 多個自動化流程。當人們問我「什麼真正有效」時，我總會想到其中一個最不重要的..."
 },
 {
  "title": "4 apps live, ~$92/mo MRR, 17 months back at it after life blew up my first attempt — AMA",
  "summary": "None of my income is passive right now, and that's the whole reason I build apps. I've got a 9-to-5, I play piano at church on the side, and I run a small ATM placement business (~$500/mo in surcharge revenue, still paying down the cards I bought the machines on). All of it stops the second I stop w",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u50u1k/4_apps_live_92mo_mrr_17_months_back_at_it_after/",
  "source": "r/EntrepreneurRideAlong",
  "category": "營收實戰",
  "mrr": "$92/mo",
  "points": 0,
  "comments": 0,
  "date": "2026-06-13",
  "title_zh": "4 個應用程式已上線，每月經常性收入約 92 美元，在人生第一次嘗試失敗後，我重新投入了 17 個月 — 有問必答",
  "summary_zh": "我目前沒有任何被動收入，這就是我開發應用程式的全部原因。我有一份朝九晚五的工作，閒暇時在教堂彈鋼琴，還經營一個小型的 ATM 放置業務（每月約 500 美元的附加費..."
 },
 {
  "title": "Shipped a freelance CRM 6 weeks ago, what working with a mobile app development agency actually cost in time and dollars",
  "summary": "Shipped 6 weeks ago, sat on this until I had real usage numbers. 230 signups, 41 paying at $14/mo, churn around 4%. small but real. &#x200B; what it is. a crm for solo freelancers who use spreadsheets and feel guilty about it. clients, projects, invoices, follow-up reminders. mobile-first because mo",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u96lrw/shipped_a_freelance_crm_6_weeks_ago_what_working/",
  "source": "r/EntrepreneurRideAlong",
  "category": "營收實戰",
  "mrr": "$14/mo",
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "6 週前發布了一個自由工作者 CRM，與行動應用程式開發公司合作實際花費的時間和金錢。",
  "summary_zh": "6 週前發布，一直等到我有實際使用數據才分享。230 個註冊，41 個付費用戶，每月支付 $14，流失率約 4%。規模雖小但真實。這是什麼？一個為使用試算表的獨立自由工作者設計的 CRM。"
 },
 {
  "title": "The customer didn't know it, but this message completely changed my day.",
  "summary": "Building solo can be a weirdly lonely experience. Most of the work happens quietly. Nobody sees the bugs you fix at 2 AM. Nobody sees the features you spend days building that nobody uses. Nobody sees the moments where you wonder if you're wasting your time. People usually only see the launch post. ",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u8f8t7/the_customer_didnt_know_it_but_this_message/",
  "source": "r/EntrepreneurRideAlong",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "客戶並不知道，但這則訊息徹底改變了我的一天。",
  "summary_zh": "獨自開發可能是一種奇怪而孤獨的經歷。大部分工作都是默默進行的。沒有人看到你在凌晨 2 點修復的錯誤。沒有人看到你花費數天開發卻無人使用的功能。沒有人看到。"
 },
 {
  "title": "One directory to rule them all!",
  "summary": "Over the last few years I've been running a portfolio of nationwide USA directories for service business niches like mobile detailing, roofing, pest control, window cleaning, pool cleaning, electricians, locksmiths etc. &#x200B; They're all large, 4000 to 5000+ listings over 400 US cities. &#x200B; ",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u8571t/one_directory_to_rule_them_all/",
  "source": "r/EntrepreneurRideAlong",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-17",
  "title_zh": "一個目錄統治所有！",
  "summary_zh": "在過去幾年裡，我一直在經營一個全國性的美國服務業目錄組合，涵蓋了行動汽車美容、屋頂修繕、病蟲害防治、窗戶清潔、泳池清潔、電工等利基市場。"
 },
 {
  "title": "I build profitable apps, but the payment system is killing my startups. Why are African/Moroccan founders locked out?",
  "summary": "Greetings everyone. For the last couple of years, I’ve been building micro-SaaS and e-commerce projects that actually solve problems and get traction. As an indie hacker, finding product-market fit should be the hardest part, right? Not for me. My biggest bottleneck is getting paid. Every time a pro",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u6tv7n/i_build_profitable_apps_but_the_payment_system_is/",
  "source": "r/EntrepreneurRideAlong",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "我開發了能獲利的應用程式，但支付系統正在扼殺我的新創公司。為什麼非洲/摩洛哥的創辦人被排除在外？",
  "summary_zh": "大家好。過去幾年，我一直在開發微型 SaaS 和電子商務專案，這些專案確實解決了問題並獲得了關注。作為一個獨立開發者 (indie hacker)，找到產品市場契合度 (product-market fit) 應該"
 },
 {
  "title": "I got fed up with all this Sloppy Tech around me so I built this",
  "summary": "Hi, You guys probably don't know me right now, since I used to be active here around 5 months ago, but now I have gotten onto a path where I know I can build a business worth millions, both personally and as a business. I'll try to be active here as much as I can now. I used to run a content marketi",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u5wm29/i_got_fed_up_with_all_this_sloppy_tech_around_me/",
  "source": "r/EntrepreneurRideAlong",
  "category": "營收實戰",
  "mrr": "$100k a month",
  "points": 0,
  "comments": 0,
  "date": "2026-06-14",
  "title_zh": "我受夠了周圍這些「馬虎的科技」，所以我做了這個",
  "summary_zh": "嗨，你們現在可能不認識我，因為我大約 5 個月前還在這裡很活躍，但現在我已經走上了一條路，我知道我可以建立一個價值數百萬的事業，無論是個人方面..."
 },
 {
  "title": "Your automation \"expert\" built you a time bomb, and they'll ghost the second it goes off.",
  "summary": "Can I vent for a sec. &#x200B; Every couple weeks I get the same call. Some business owner who paid an \"automation expert\" good money, and now they've got a workflow that works... sometimes. On a good day. If the wind's blowing the right way. And they want me to figure out why their \"fully automated",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1uab57i/your_automation_expert_built_you_a_time_bomb_and/",
  "source": "r/EntrepreneurRideAlong",
  "category": "工作流自動化",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-19",
  "title_zh": "你的自動化「專家」為你埋下了定時炸彈，一旦引爆他們就會消失。",
  "summary_zh": "我可以抱怨一下嗎？每隔幾週，我都會接到相同的電話。某個企業主花大錢請了「自動化專家」，結果現在他們得到的工作流程卻是... 有時能用。在好的情況下..."
 },
 {
  "title": "I regret not setting up the CRM earlier",
  "summary": "many of you may know me from my last post about starting a Reddit growth agency with no CRM or website after I got laid off and didn't hear after two interviews and generated $15k in pipeline in first month I use a tool for LinkedIn outreach and today while setting up the CRM I noticed there are so ",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u70lq0/i_regret_not_setting_up_the_crm_earlier/",
  "source": "r/EntrepreneurRideAlong",
  "category": "營收實戰",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-16",
  "title_zh": "我後悔沒有早點設定 CRM",
  "summary_zh": "許多人可能從我上一篇關於在被解僱後，沒有 CRM 或網站就開始 Reddit 成長代理業務的貼文認識我，兩次面試都沒有下文，但在第一個月就創造了 $15k 的潛在客戶"
 },
 {
  "title": "15 and launched Xenith after 6 months of evenings. No-streak, no-ad productivity dashboard.",
  "summary": "I’m 15 and bootstrapped this whole thing. Nothing fancy. I just got tired of bouncing between 5 billion different apps for tools I need. so I made something that didn’t annoy me.. Xenith is basically a clean dashboard for habits, routines, and projects. That’s it. What was hard: Honestly, keeping it",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u6oxpj/15_and_launched_xenith_after_6_months_of_evenings/",
  "source": "r/EntrepreneurRideAlong",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "我 15 歲，在晚上花了 6 個月後推出了 Xenith。這是一個無連勝紀錄、無廣告的生產力儀表板。",
  "summary_zh": "我 15 歲，而且是白手起家完成這個專案的。沒有什麼花俏的功能。我只是厭倦了為了我需要的工具，在數不清的應用程式之間切換。所以我做了一個不會讓我煩躁的東西... Xenith 基本上就是..."
 },
 {
  "title": "How to get custom vending machines built for your product",
  "summary": "Quick brain dump on getting custom vending machines built since this comes up a lot Dispense path matters more than anything else in the spec sheet. Coils only handle rectangular durable stuff, anything fragile or irregular needs conveyor belt shelves or elevator dispensing, and most cheap machines ",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u69jqz/how_to_get_custom_vending_machines_built_for_your/",
  "source": "r/EntrepreneurRideAlong",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-15",
  "title_zh": "如何為你的產品訂製自動販賣機",
  "summary_zh": "關於訂製自動販賣機的快速腦力激盪，因為這經常被問到。出貨路徑比規格表上的任何其他東西都重要。螺旋彈簧只能處理矩形耐用的物品，任何..."
 },
 {
  "title": "Users rarely tell you why they churn",
  "summary": "I used to think churn would be obvious. Like someone would cancel and tell us the pricing was wrong, or that a feature was missing, or that the product just wasn’t for them. Most of the time, that didn’t happen. People signed up, tried the product, maybe even completed onboarding, and then just neve",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u4sl1y/users_rarely_tell_you_why_they_churn/",
  "source": "r/EntrepreneurRideAlong",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-13",
  "title_zh": "用戶很少告訴你他們為什麼流失",
  "summary_zh": "我以前認為用戶流失的原因會很明顯。比如有人會取消訂閱並告訴我們定價不對，或者缺少某個功能，或者產品不適合他們。大部分時間，那確實..."
 },
 {
  "title": "Solo dev ride-along: launching a funny iOS app for social overthinking with zero audience",
  "summary": "I launched a small iOS app called Overthought. It gives brutally honest verdicts on social/dating situations people are overthinking. I am treating the first month as a distribution test, not a product-building sprint. The app is already live, so the question is not “what feature should I add?” The ",
  "url": "https://www.reddit.com/r/EntrepreneurRideAlong/comments/1u9g3ga/solo_dev_ridealong_launching_a_funny_ios_app_for/",
  "source": "r/EntrepreneurRideAlong",
  "category": "SaaS 經營",
  "mrr": null,
  "points": 0,
  "comments": 0,
  "date": "2026-06-18",
  "title_zh": "獨立開發者實錄：在零受眾的情況下，推出一款針對社交過度思考的有趣 iOS 應用程式。",
  "summary_zh": "我推出了一款名為 Overthought 的小型 iOS 應用程式。它對人們過度思考的社交/約會情境給出殘酷而誠實的判斷。我將第一個月份視為發行測試，而不是產品..."
 }
];
